import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
let seq=12000,passed=0;const id=()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,'0')}`;
const w=id(),admin=id(),tech=id(),ad=id(),td=id(),source=id(),target=id();
const db=new PGlite();
await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");
await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL(`../supabase/migrations/${f}`,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1),($2)',[admin,tech]);await db.query("insert into private.workshops(id,name) values($1,'Fictional return validation')",[w]);await db.query("insert into private.members values($1,$2,'Fictional admin','admin',true,true),($1,$3,'Fictional tech','technician',false,true)",[w,admin,tech]);
let actor=admin,dev=ad;
const snap=async()=>(await db.query('select public.device_snapshot($1,$2) r',[w,dev])).rows[0].r;
async function login(user,device){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[device,user]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,session_id:device})]);await db.exec('set role authenticated');actor=user;dev=device;await snap();}
const draft=()=>({plate:'9010FIC',country:'ES',vin:'FICTIONAL-RETURNS',vehicle:'Fictional car',engine:'2020',client:'Fictional owner',phone:'',km:100,symptom:'New original symptom',tasks:[{id:id(),title:'New diagnosis',estimateMinutes:30,assignees:[tech]}]});
async function op(kind,oid,p,rev,opid=id()){const record={id:opid,orderId:oid,actorId:actor,kind,baseRevision:rev??(await snap()).orders.find(o=>o.id===oid)?.revision??0,at:new Date().toISOString(),payload:p};return {record,result:(await db.query('select public.apply_operation($1,$2,$3) r',[w,dev,record])).rows[0].r};}
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
try{
 await login(admin,ad);assert.equal((await op('receive',source,draft())).result.status,'accepted');await login(tech,td);
 const payload=(stage='result')=>({stage,text:'Fictional measured 12.2 V',context:'Ignition off; fictitious meter',dtcs:'P0000',source:'Fictional authorized reference',confirmed:false});let first,review,withdrawal;
 await test('Hypotheses and measurements append without authorization, time or consumption',async()=>{const before=(await snap()).orders.find(o=>o.id===source);first=await op('diagnosis_add',source,payload());assert.equal(first.result.status,'accepted');assert.equal((await op('diagnosis_add',source,payload('hypothesis'),0)).result.status,'accepted');const o=(await snap()).orders.find(o=>o.id===source);assert.equal(o.diagnosisNotebook.length,2);assert.deepEqual(o.tasks,before.tasks);assert.deepEqual(o.times,before.times);assert.deepEqual(o.parts,before.parts);});
 await test('Conclusions and verification require human confirmation; price injection fails',async()=>{for(const p of [payload('conclusion'),payload('verification'),{...payload(),confirmed:'yes'},{...payload(),amountCents:1}])assert.equal((await op('diagnosis_add',source,p)).result.status,'conflict');assert.equal((await op('diagnosis_add',source,{...payload('conclusion'),confirmed:true})).result.status,'accepted');});
 await test('Lost response is once and altered original command identity is refused',async()=>{assert.deepEqual((await db.query('select public.apply_operation($1,$2,$3) r',[w,dev,first.record])).rows[0].r,first.result);await assert.rejects(()=>db.query('select public.apply_operation($1,$2,$3)',[w,dev,{...first.record,payload:{...payload(),text:'Changed'}}]),/Idempotency/i);assert.equal((await snap()).orders.find(o=>o.id===source).diagnosisNotebook.length,3);});
 await test('Correction appends its parent and stale reviews cannot replace it',async()=>{const p={...payload(),text:'Corrected fictional value',replacesId:first.record.id,reason:'Fictional transcription correction'};assert.equal((await op('diagnosis_add',source,p,0)).result.status,'conflict');review=await op('diagnosis_add',source,p);assert.equal(review.result.status,'accepted');const rows=(await snap()).orders.find(o=>o.id===source).diagnosisNotebook;assert.equal(rows[0].id,first.record.id);assert.equal(rows[0].text,payload().text);assert.equal(rows.at(-1).replacesId,first.record.id);assert.equal((await op('diagnosis_add',source,p)).result.status,'conflict');});
 await test('Withdrawal retains evidence and its retry creates no second withdrawal',async()=>{withdrawal=await op('diagnosis_withdraw',source,{sourceId:review.record.id,reason:'Fictional fault reappeared'});assert.equal(withdrawal.result.status,'accepted');assert.deepEqual((await db.query('select public.apply_operation($1,$2,$3) r',[w,dev,withdrawal.record])).rows[0].r,withdrawal.result);assert.equal((await snap()).orders.find(o=>o.id===source).diagnosisNotebook.filter(x=>x.stage==='withdrawal').length,1);assert.equal((await op('diagnosis_withdraw',source,{sourceId:first.record.id,reason:'Already superseded'})).result.status,'conflict');});
 await test('A technician cannot correct another author entry; office can review it',async()=>{await login(admin,ad);const a=await op('diagnosis_add',source,payload());await login(tech,td);const p={...payload(),replacesId:a.record.id,reason:'Review another author'};assert.equal((await op('diagnosis_add',source,p)).result.status,'conflict');await login(admin,ad);assert.equal((await op('diagnosis_add',source,p)).result.status,'accepted');});
 await test('Technical evidence after issuance leaves original document and financial data intact',async()=>{await db.exec('reset role');await db.query('update private.orders set data=data||$1 where workshop_id=$2 and id=$3',[{document:{totalCents:12345,clientSnapshot:'Original recipient'},quality:{result:'Prior verification'}},w,source]);await login(tech,td);const original=(await snap()).orders.find(o=>o.id===source);assert.equal((await op('diagnosis_add',source,payload())).result.status,'accepted');await login(admin,ad);const o=(await snap()).orders.find(o=>o.id===source);assert.equal(o.document.totalCents,12345);assert.equal(o.document.clientSnapshot,'Original recipient');assert.equal(o.quality,null);assert.deepEqual(o.parts,original.parts);assert.deepEqual(o.times,original.times);});
 await test('Unassigned technicians and private helper access are denied',async()=>{await db.exec('reset role');await db.query("update private.orders set data=jsonb_set(data,'{tasks,0,assignees}','[]') where workshop_id=$1 and id=$2",[w,source]);await login(tech,td);assert.equal((await op('diagnosis_add',source,payload())).result.status,'conflict');await assert.rejects(()=>db.query("select private.diagnosis_entry('{}','{}','diagnosis_add',$1,'x','technician',$2,now(),0,0)",[tech,id()]),/permission denied/);await login(admin,ad);});
 await test('Complete export preserves entries, withdrawals, original operation evidence and audit',async()=>{const a=(await db.query('select public.export_workshop($1,$2) r',[w,dev])).rows[0].r;const o=a.tables.orders.find(o=>o.id===source);assert.equal(o.data.diagnosisNotebook.length,8);assert.equal(o.data.document.totalCents,12345);assert.ok(a.tables.operations.find(x=>x.id===first.record.id));assert.equal(a.tables.audit.filter(x=>x.kind==='diagnosis_withdraw').length,1);});
 console.log(`${passed} diagnosis checks passed in PostgreSQL/PGlite with synthetic Auth.`);
}finally{await db.close();}
