import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
let sequence=41000,passed=0;
const id=()=>`00000000-0000-4000-8000-${String(sequence++).padStart(12,'0')}`;
const w=id(),other=id(),admin=id(),office=id(),tech=id(),foreign=id(),dev=id(),od=id(),td=id(),fd=id(),recoveryDevice=id(),legacyDevice=id();
const profile={country:'ES',legalForm:'company',territory:'common',sii:'no',clients:'mixed',turnover:'under_8m',taxSystem:'iva'};
const files=(await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort();
async function setup(){
 const db=new PGlite();
 await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");
 await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
 for(const f of files)await db.exec(await readFile(new URL(`../supabase/migrations/${f}`,import.meta.url),'utf8'));
 await db.query('insert into auth.users values($1),($2),($3),($4)',[admin,office,tech,foreign]);
 await db.query("insert into private.workshops(id,name) values($1,'Fictional fiscal draft'),($2,'Other isolated workshop')",[w,other]);
 await db.query("insert into private.members values($1,$2,'Admin','admin',true,true),($3,$4,'Foreign','admin',true,true)",[w,admin,other,foreign]);
 return db;
}
async function login(db,user,d,ws=w){
 await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[d,user]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,session_id:d})]);await db.exec('set role authenticated');await db.query('select public.device_snapshot($1,$2)',[ws,d]);
}
const read=(db,d=dev,ws=w)=>db.query('select public.fiscal_drafts($1,$2) r',[ws,d]).then(r=>r.rows[0].r);
const command=(db,action,p,cid=id(),d=dev,ws=w)=>db.query('select public.fiscal_draft_command($1,$2,$3,$4,$5) r',[ws,d,cid,action,p]).then(r=>r.rows[0].r);
const line=()=>({id:id(),description:'Fictional part',unitCents:3333,quantityMilli:1500,discountBps:1250,taxBps:2100,tax:'iva',treatment:'taxable'});
async function payload(db,extra={},d=dev){
 const h=(await read(db,d)).heads.find(h=>h.issuer_nif==='B12345678'&&h.installation==='sandbox-a');
 return {issuerNif:'B12345678',installation:'sandbox-a',prefix:'ENSAYO-A',expectedSequence:h?.last_sequence??0,expectedHash:h?.last_hash??'',reason:'Fictional technical draft',issueDate:'2026-10-07',recipient:{name:'Fictional recipient',nif:'12345678Z'},lines:[line()],...extra};
}
async function test(name,fn){await fn();passed++;console.log('PASS '+name);}
const db=await setup(),target=await setup(),legacy=await setup();let first,firstPayload,firstId,withdrawal,archive,legacyArchive;
try{
 await db.query("insert into private.members values($1,$2,'Office','office',true,true),($1,$3,'Tech','technician',false,true)",[w,office,tech]);
 await login(db,admin,dev);
 await db.query("select public.management_command($1,$2,$3,'fiscal_profile_save',$4)",[w,dev,id(),{revision:0,reason:'Fictional profile',profile}]);
 legacyArchive=(await db.query('select public.export_workshop($1,$2) r',[w,dev])).rows[0].r;
 await test('Append computes the amount and allocates only a sandbox number',async()=>{
  firstPayload=await payload(db);firstId=id();first=await command(db,'fiscal_draft_append',firstPayload,firstId);
  assert.equal(first.number,1);assert.equal(first.sequence,1);assert.equal(first.emissionEnabled,false);assert.equal(first.transmissionEnabled,false);
  const r=(await read(db)).records[0];assert.equal(r.body.calculation.baseCents,4375);assert.equal(r.body.calculation.taxCents,919);assert.equal(r.body.calculation.totalCents,5294);assert.equal(r.previous_hash,'');assert.equal(r.ledger_hash,first.ledgerHash);
 });
 await test('Lost reply retries return the original identity, number and fingerprint',async()=>{assert.deepEqual(await command(db,'fiscal_draft_append',firstPayload,firstId),first);assert.equal((await read(db)).records.length,1);});
 await test('Reusing command identity with changed data fails',async()=>{await assert.rejects(()=>command(db,'fiscal_draft_append',{...firstPayload,reason:'Changed'},firstId),/reused/);});
 await test('Stale head or altered expected fingerprint fails without consuming a number',async()=>{await assert.rejects(()=>command(db,'fiscal_draft_append',firstPayload),/chain conflict/);const p=await payload(db);await assert.rejects(()=>command(db,'fiscal_draft_append',{...p,expectedHash:'F'.repeat(64)}),/chain conflict/);assert.equal((await read(db)).series[0].last_number,1);});
 await test('Two queued contenders on the same head have exactly one effect',async()=>{const p=await payload(db);const results=await Promise.allSettled([command(db,'fiscal_draft_append',p),command(db,'fiscal_draft_append',p)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await read(db)).records.length,2);});
 await test('Prefixes have their own counters and share the installation chain',async()=>{const r=await command(db,'fiscal_draft_append',await payload(db,{prefix:'ENSAYO-B'}));assert.equal(r.number,1);assert.equal(r.sequence,3);});
 await test('Another installation starts a distinct chain',async()=>{const r=await command(db,'fiscal_draft_append',await payload(db,{installation:'sandbox-b',expectedSequence:0,expectedHash:''}));assert.equal(r.sequence,1);assert.equal(r.number,1);});
 await test('Another issuer is isolated even with the same installation and series',async()=>{const r=await command(db,'fiscal_draft_append',await payload(db,{issuerNif:'A87654321',expectedSequence:0,expectedHash:''}));assert.equal(r.sequence,1);});
 await test('Invalid lines, dates, treatment and activation are rejected atomically',async()=>{
  const good=await payload(db),before=await read(db);
  for(const changes of [{emissionEnabled:true},{prefix:'REAL-2026'},{issueDate:'2026-02-30'},{recipient:{name:'',nif:'12345678Z'}},{lines:[]},{lines:[{...line(),unitCents:-1}]},{lines:[{...line(),quantityMilli:0}]},{lines:[{...line(),discountBps:10001}]},{lines:[{...line(),tax:'invented'}]},{lines:[{...line(),treatment:'exempt',taxBps:0,reason:''}]},{lines:[{...line(),treatment:'exempt',reason:'Fictional'}]},{lines:[{...line(),unitCents:1000000000000,quantityMilli:1000000000}]}])await assert.rejects(()=>command(db,'fiscal_draft_append',{...good,...changes}));
  assert.deepEqual(await read(db),before);
 });
 await test('Reasoned special treatment is explicit, with zero tax',async()=>{const r=await command(db,'fiscal_draft_append',await payload(db,{lines:[{...line(),taxBps:0,treatment:'exempt',reason:'Fictional exemption for structural test'}]}));assert.equal((await read(db)).records.find(x=>x.id===r.id).body.calculation.taxCents,0);});
 await test('Half cents round per line and quantities remain exact',async()=>{await db.exec('reset role');const r=(await db.query('select private.fiscal_draft_calculation($1) r',[[{...line(),unitCents:1,quantityMilli:500,discountBps:0,taxBps:5000},{...line(),unitCents:1,quantityMilli:500,discountBps:0,taxBps:5000}]])).rows[0].r;assert.equal(r.baseCents,2);assert.equal(r.taxCents,2);assert.equal(r.totalCents,4);await login(db,admin,dev);});
 await test('Withdrawal retains the original and never recycles its number',async()=>{const p=await payload(db);for(const key of ['prefix','lines','issueDate','recipient'])delete p[key];p.targetId=firstId;const cid=id();withdrawal=await command(db,'fiscal_draft_withdraw',p,cid);assert.equal(withdrawal.number,1);const records=(await read(db)).records;assert.equal(records.find(x=>x.id===firstId).ledger_hash,first.ledgerHash);assert.equal(records.find(x=>x.id===cid).target_id,firstId);assert.deepEqual(await command(db,'fiscal_draft_withdraw',p,cid),withdrawal);await assert.rejects(()=>command(db,'fiscal_draft_withdraw',{...p,expectedSequence:withdrawal.sequence,expectedHash:withdrawal.ledgerHash}),/already withdrawn/);const n=await command(db,'fiscal_draft_append',await payload(db));assert.equal(n.number,4);});
 await test('Withdrawals cannot cross installation, issuer or replace original data',async()=>{const p=await payload(db);for(const key of ['prefix','lines','issueDate','recipient'])delete p[key];p.targetId=firstId;await assert.rejects(()=>command(db,'fiscal_draft_withdraw',{...p,installation:'sandbox-c',expectedSequence:0,expectedHash:''}),/not found/);await assert.rejects(()=>command(db,'fiscal_draft_withdraw',{...p,lines:[line()]}),/replace/);});
 await test('Office and technician cannot read or append private fiscal drafts',async()=>{for(const [user,d] of [[office,od],[tech,td]]){await login(db,user,d);await assert.rejects(()=>read(db,d),/Administrator/);await assert.rejects(()=>command(db,'fiscal_draft_append',firstPayload,id(),d),/Administrator/);}await login(db,admin,dev);});
 await test('A member of another workshop cannot read this ledger',async()=>{await login(db,foreign,fd,other);await assert.rejects(()=>read(db,fd,w),/Membership/);assert.equal((await read(db,fd,other)).records.length,0);await login(db,admin,dev);});
 await test('Direct client reads, private helpers and anonymous RPCs are denied',async()=>{await assert.rejects(()=>db.query('select * from private.fiscal_draft_records'),/permission denied/);await assert.rejects(()=>db.query('select private.validate_fiscal_drafts($1)',[w]),/permission denied/);await db.exec('reset role;set role anon');await assert.rejects(()=>read(db),/permission denied/);await db.exec('reset role');await db.query('select private.validate_fiscal_drafts($1)',[w]);await login(db,admin,dev);});
 await test('Original ledger entries cannot be updated or deleted',async()=>{await db.exec('reset role');await assert.rejects(()=>db.query("update private.fiscal_draft_records set body='{}' where id=$1",[firstId]),/immutable/i);await assert.rejects(()=>db.query('delete from private.fiscal_draft_records where id=$1',[firstId]),/immutable/i);await login(db,admin,dev);});
 await test('Current backup contains every series, record, receipt and reasoned audit',async()=>{archive=(await db.query('select public.export_workshop($1,$2) r',[w,dev])).rows[0].r;assert.equal(archive.databaseVersion,14);assert.equal(archive.tables.fiscal_draft_records.length,8);assert.equal(archive.tables.fiscal_draft_heads.length,3);assert.equal(archive.tables.command_receipts.filter(r=>r.action.startsWith('fiscal_draft_')).length,8);assert.equal(archive.tables.audit.filter(r=>r.kind.startsWith('fiscal_draft_')).length,8);});
 await login(target,admin,recoveryDevice);
 const restore=(a,rid=id())=>target.query('select public.restore_workshop($1,$2,$3,$4) r',[w,recoveryDevice,rid,a]).then(r=>r.rows[0].r);
 await test('Missing ledger table rejects recovery before it can be mistaken for an empty series',async()=>{const a=structuredClone(archive);delete a.tables.fiscal_draft_series;await assert.rejects(()=>restore(a),/table missing/);});
 await test('Tampered fingerprint, missing records, receipts or audit reject recovery atomically',async()=>{for(const modify of [a=>a.tables.fiscal_draft_records[0].ledger_hash='A'.repeat(64),a=>a.tables.fiscal_draft_records.pop(),a=>a.tables.fiscal_draft_heads[0].last_sequence++,a=>a.tables.fiscal_draft_series[0].last_number++,a=>a.tables.command_receipts=a.tables.command_receipts.filter(x=>x.id!==firstId),a=>a.tables.audit=a.tables.audit.filter(x=>x.operation_id!==firstId)]){const a=structuredClone(archive);modify(a);await assert.rejects(()=>restore(a));assert.equal((await read(target,recoveryDevice)).records.length,0);}});
 await test('Recovery preserves immutable contents and freezes restored installations',async()=>{const rid=id(),r=await restore(archive,rid);assert.equal(r.restored,true);const data=await read(target,recoveryDevice);assert.deepEqual(data.records,[...archive.tables.fiscal_draft_records].sort((a,b)=>a.issuer_nif.localeCompare(b.issuer_nif)||a.installation.localeCompare(b.installation)||a.sequence-b.sequence));assert.ok(data.heads.every(x=>x.restored));assert.deepEqual(await restore(archive,rid),r);const p=await payload(target,{},recoveryDevice);await assert.rejects(()=>command(target,'fiscal_draft_append',p,id(),recoveryDevice),/frozen/);const fresh=await command(target,'fiscal_draft_append',{...p,installation:'recovery-new',expectedSequence:0,expectedHash:''},id(),recoveryDevice);assert.equal(fresh.number,1);assert.deepEqual(await restore(archive,rid),r);assert.equal((await read(target,recoveryDevice)).heads.find(x=>x.installation==='recovery-new').restored,false);});
 await test('Version 13 archives remain compatible but cannot hide nonempty fiscal data',async()=>{const a=structuredClone(archive);a.databaseVersion=13;await login(legacy,admin,legacyDevice);await assert.rejects(()=>legacy.query('select public.restore_workshop($1,$2,$3,$4)',[w,legacyDevice,id(),a]),/unversioned/);const clean=structuredClone(legacyArchive);clean.databaseVersion=13;for(const key of ['fiscal_draft_heads','fiscal_draft_series','fiscal_draft_records'])delete clean.tables[key];const r=(await legacy.query('select public.restore_workshop($1,$2,$3,$4) r',[w,legacyDevice,id(),clean])).rows[0].r;assert.equal(r.restored,true);assert.equal((await read(legacy,legacyDevice)).records.length,0);});
 await test('SII and foral preparation cannot silently choose the draft circuit',async()=>{let revision=1;for(const changes of [{sii:'yes'},{sii:'unknown'},{territory:'bizkaia'}]){await db.query("select public.management_command($1,$2,$3,'fiscal_profile_save',$4)",[w,dev,id(),{revision:revision++,reason:'Fictional incompatible circuit',profile:{...profile,...changes}}]);const p=await payload(db);await assert.rejects(()=>command(db,'fiscal_draft_append',p),/covers|foral|SII/);} });
 await test('Revoked Auth session also blocks an idempotent retry',async()=>{await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[dev]);await db.exec('set role authenticated');await assert.rejects(()=>command(db,'fiscal_draft_append',firstPayload,firstId),/session/i);});
 console.log(`${passed} fiscal draft ledger checks passed in PostgreSQL/PGlite; queued calls are not a multi-connection concurrency proof. No fiscal emission or hosted Auth HTTP.`);
}finally{await db.close();await target.close();await legacy.close();}
