import {PGlite} from '@electric-sql/pglite';import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
let seq=24000,passed=0;const id=()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,'0')}`;
const w=id(),other=id(),admin=id(),a=id(),b=id(),dev=id(),td=id(),oid=id(),otherOrder=id(),task=id(),pid=id();const db=new PGlite();
await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort())await db.exec(await readFile(new URL(`../supabase/migrations/${f}`,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1),($2),($3)',[admin,a,b]);await db.query("insert into private.workshops(id,name) values($1,'Fictional maintenance'),($2,'Isolated workshop')",[w,other]);await db.query("insert into private.members values($1,$2,'Admin','admin',true,true),($1,$3,'Tech','technician',false,true),($1,$4,'Other tech','technician',false,true),($5,$2,'Admin','admin',true,true)",[w,admin,a,b,other]);
let device=dev;async function login(user,dd){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[dd,user]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,session_id:dd})]);await db.exec('set role authenticated');device=dd;await snap();}
const snap=async()=>(await db.query('select public.device_snapshot($1,$2) r',[w,device])).rows[0].r;
const command=async(action,p,cid=id())=>(await db.query('select public.fleet_command($1,$2,$3,$4,$5) r',[w,device,cid,action,p])).rows[0].r;
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};let vehicle,owner;
const group=async(overrides={})=>({id:pid,revision:(await snap()).fleets.revision,name:'Fictional fleet',organization:'Verified fictional company',reason:'Fictional group',...overrides});
const attach=async(overrides={})=>({id:pid,revision:(await snap()).fleets.revision,membershipId:task,vehicleId:vehicle,ownerId:owner,reference:'Fictional unit',evidence:'Membership checked by office',reason:'Fictional attachment',...overrides});
try{
 await login(admin,dev);
 const op={id:id(),orderId:oid,actorId:admin,kind:'receive',baseRevision:0,at:new Date().toISOString(),payload:{plate:'9200FIC',country:'ES',vin:'FICTIONAL-FLEET',vehicle:'Fictional',engine:'2020',client:'Fictional owner',phone:'',km:128000,symptom:'Fictional',tasks:[{id:id(),title:'Diagnosis',estimateMinutes:30,assignees:[a]}]}};
 assert.equal((await db.query('select public.apply_operation($1,$2,$3) r',[w,device,op])).rows[0].r.status,'accepted');const o=(await snap()).orders[0];vehicle=o.vehicleId;owner=o.ownerId;
 let p,cid=id();
 await test('Office grouping and membership preserve repairs and original owner evidence',async()=>{const before=(await snap()).orders;p=await group();await command('fleet_group',p,cid);await command('fleet_attach',await attach());assert.deepEqual((await snap()).orders,before);assert.equal((await snap()).fleets.groups[0].memberships[0].ownerId,owner);});
 await test('Lost reply retains identity and rejects changed command reuse',async()=>{await command('fleet_group',p,cid);assert.equal((await snap()).fleets.groups.length,1);await assert.rejects(()=>command('fleet_group',{...p,name:'Changed'},cid),/ID reused/);});
 await test('Versions preserve prior group and organization',async()=>{await command('fleet_group',await group({name:'Revised'}));const g=(await snap()).fleets.groups[0];assert.equal(g.versions.length,2);assert.equal(g.versions[0].name,'Fictional fleet');});
 await test('Stale writes, foreign owner or vehicle, and missing evidence fail atomically',async()=>{for(const p of [{revision:0},{vehicleId:id()},{ownerId:id()},{evidence:''}])await assert.rejects(async()=>command('fleet_attach',await attach({...p,membershipId:id()})));assert.equal((await snap()).fleets.groups[0].memberships.length,1);});
 const otherGroup=id(),newMid=id();
 await test('One active membership requires explicit removal before transfer',async()=>{await command('fleet_group',await group({id:otherGroup}));await assert.rejects(async()=>command('fleet_attach',await attach({id:otherGroup,membershipId:newMid})),/previous/);await command('fleet_detach',{id:pid,revision:(await snap()).fleets.revision,membershipId:task,reason:'Transfer checked'});await command('fleet_attach',await attach({id:otherGroup,membershipId:newMid}));assert.equal((await snap()).fleets.groups.find(g=>g.id===pid).memberships[0].status,'removed');});
 await test('Archive requires removal and cannot overwrite historical fleet',async()=>{await assert.rejects(()=>command('fleet_archive',{id:otherGroup,revision:6,reason:'Archive'}));await command('fleet_archive',{id:pid,revision:(await snap()).fleets.revision,reason:'Archive original fleet'});await assert.rejects(async()=>command('fleet_group',await group()),/preserve/);});
 await test('Owner changes retain original binding and require new verification',async()=>{await db.exec('reset role');await db.query('update private.vehicle_profiles set owner_id=$1,owner_data=$2 where workshop_id=$3 and vehicle_id=$4',[id(),{name:'Fictional new owner',phone:''},w,vehicle]);await db.exec('set role authenticated');const s=await snap(),m=s.fleets.groups.find(g=>g.id===otherGroup).memberships[0];assert.equal(m.ownerId,owner);assert.notEqual(s.vehicleProfiles[0].ownerId,owner);assert.equal(m.ownerSnapshot.name,'Fictional owner');});
 await test('Technicians cannot read personal fleet evidence or mutate groups',async()=>{await login(a,td);assert.deepEqual((await snap()).fleets,{revision:0,groups:[]});await assert.rejects(async()=>command('fleet_group',await group()),/Office/);await login(admin,dev);});
 await test('Archive contains memberships, versions, audit and receipts',async()=>{const ar=(await db.query('select public.export_workshop($1,$2) r',[w,dev])).rows[0].r;assert.equal(ar.databaseVersion,14);assert.deepEqual(ar.tables.fleet_state[0].data,(await snap()).fleets);await db.exec('reset role');await db.query('select private.validate_fleets($1,$2)',[w,ar.tables.fleet_state[0].data]);await db.exec('set role authenticated');});
 await test('Workshop boundaries, direct table access and anonymous calls are denied',async()=>{assert.deepEqual((await db.query('select public.workshop_snapshot($1) r',[other])).rows[0].r.fleets,{revision:0,groups:[]});await assert.rejects(()=>db.query('select * from private.fleet_state'),/permission denied/);await db.exec('reset role;set role anon');await assert.rejects(()=>command('fleet_group',{}),/permission denied/);await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[dev]);await db.exec('set role authenticated');await assert.rejects(()=>command('fleet_group',p,cid),/session/);});
 console.log(`${passed} fleet checks passed in PostgreSQL/PGlite with synthetic Auth.`);
}finally{await db.close();}
