import {readFile,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const cfg=JSON.parse(await readFile(process.env.TF_QA_CONFIG,'utf8'));if(!cfg.approved||!Object.values(cfg.users).every(u=>u.email.endsWith('@example.invalid')))throw Error('Approved isolated accounts required');
const sha=x=>createHash('sha256').update(x).digest('hex'),clients={source:{},destination:{}},checks=[];
const proof={date:new Date().toISOString(),runId:cfg.runId,source:cfg.projects.source.id,destination:cfg.projects.destination.id,workshop:cfg.workshop,environment:'Two real hosted Supabase projects; Auth, PostgREST, private Storage and Edge HTTP',nativeValidated:false,physicalDeviceValidated:false,checks,passed:false};
const evidence=process.env.TF_QA_EVIDENCE;let retained;try{retained=JSON.parse(await readFile(evidence,'utf8'));if(retained.runId!==cfg.runId)throw Error('Wrong fixture');}catch(e){if(e.code!=='ENOENT')throw e;}
cfg.recovery??={id:randomUUID(),devices:{admin:randomUUID(),tech1:randomUUID(),outsider:randomUUID()}};
await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));let archive;
async function request(project,path,who,body,{method='POST',bytes,jwt}={}){const p=cfg.projects[project],headers={apikey:p.anon,'Content-Type':bytes?'image/jpeg':'application/json'};if(who||jwt)headers.Authorization='Bearer '+(jwt??clients[project][who]);const r=await fetch(p.url+path,{method,headers,body:bytes??(body===undefined?undefined:JSON.stringify(body)),signal:AbortSignal.timeout(45000)});let data={};try{data=await r.json()}catch{}return {ok:r.ok,status:r.status,data};}
async function rpc(p,who,name,body,deny=false){const r=await request(p,'/rest/v1/rpc/'+name,who,body);if(deny){assert.equal(r.ok,false,name);return r;}if(!r.ok)throw Error(name+' '+r.status+' '+(r.data.message??''));return r.data;}
const dev=(p,who)=>p==='source'?cfg.users[who].device:cfg.recovery.devices[who];
const snap=(p,who,device_id=dev(p,who))=>rpc(p,who,'device_snapshot',{workshop_id:cfg.workshop,device_id});
const photo=(p,who,body)=>request(p,'/functions/v1/workshop-photos',who,{workshopId:cfg.workshop,deviceId:dev(p,who),...body});
async function readPhoto(p,id){const r=await fetch(cfg.projects[p].url+'/functions/v1/workshop-photos',{method:'POST',headers:{apikey:cfg.projects[p].anon,Authorization:'Bearer '+clients[p].admin,'Content-Type':'application/json'},body:JSON.stringify({workshopId:cfg.workshop,deviceId:dev(p,'admin'),action:'read',photoId:id}),signal:AbortSignal.timeout(45000)});assert.equal(r.ok,true,'Private photo '+p);assert.match(r.headers.get('cache-control'),/no-store/);return Buffer.from(await r.arrayBuffer());}
async function check(name,f){if(retained?.checks?.includes(name)&&!name.startsWith('Five fictitious')&&!name.startsWith('Source JWT')){checks.push(name);console.log('RETAINED '+name);if(name.startsWith('Current format'))archive=cfg.recovery.archive;return;}await f();checks.push(name);console.log('PASS '+name);await writeFile(evidence,JSON.stringify({...proof,totalChecks:checks.length},null,2));}
try{
 await check('Five fictitious identities authenticate in both projects without copying their passwords or sessions',async()=>{for(const p of ['source','destination'])for(const [who,u]of Object.entries(cfg.users)){const r=await request(p,'/auth/v1/token?grant_type=password',null,{email:u.email,password:'Qa!2026'+sha(cfg.capability+u.id+cfg.projects[p].url)});assert.equal(r.ok,true,'Login '+p+' '+who);assert.equal(r.data.user.id,u.id);clients[p][who]=r.data.access_token;}assert.notEqual(clients.source.admin,clients.destination.admin);await snap('source','admin');await snap('destination','admin');});
 await check('Source JWT cannot authenticate to the destination',async()=>{assert.equal((await request('destination','/auth/v1/user',null,undefined,{method:'GET',jwt:clients.source.admin})).ok,false);});
 await check('Current format 13 exports documents, private photos, all module state and command receipts',async()=>{await snap('source','admin');archive=cfg.recovery.archive??await rpc('source','admin','export_workshop',{workshop_id:cfg.workshop,device_id:dev('source','admin')});assert.equal(archive.databaseVersion,13);assert.equal(archive.authExcluded,true);assert.ok(archive.tables.documents.length>0);for(const k of ['planning_state','maintenance_state','fleet_state','case_library','inventory_state','command_receipts'])assert.ok(archive.tables[k].length>0,k);assert.equal(JSON.stringify(archive).includes(clients.source.admin),false);assert.ok(archive.photoFiles.every(x=>x.filePresent));proof.sourceOperationCount=archive.tables.operations.length;cfg.recovery.archive=archive;await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));});
 await check('Restoration is idempotent and rejects altered content under the same identity',async()=>{await snap('destination','admin');const body={workshop_id:cfg.workshop,device_id:dev('destination','admin'),restore_id:cfg.recovery.id,archive};const r=await rpc('destination','admin','restore_workshop',body);assert.equal(r.restored,true);assert.deepEqual(await rpc('destination','admin','restore_workshop',body),r);await rpc('destination','admin','restore_workshop',{...body,archive:{...archive,exportedAt:new Date().toISOString()}},true);});
 await check('Historical source devices are retired and never regain authority',async()=>{for(const who of ['admin','tech1'])await rpc('destination',who,'device_snapshot',{workshop_id:cfg.workshop,device_id:cfg.users[who].device},true);await snap('destination','tech1');const s=await snap('destination','admin');assert.ok(s.devices.filter(x=>Object.values(cfg.users).some(u=>u.device===x.id)).every(x=>x.retiredAt));});
 await check('Incomplete recovery blocks new work until every original photo is verified',async()=>{const r=await rpc('destination','admin','apply_operation',{workshop_id:cfg.workshop,device_id:dev('destination','admin'),operation:{id:randomUUID(),orderId:randomUUID(),actorId:cfg.users.admin.id,kind:'receive',baseRevision:0,at:new Date().toISOString(),payload:{}}},true);assert.match(r.data.message,/Restore/);});
 await check('Original private photo bytes and hashes are recovered through ordinary authenticated upload',async()=>{for(const f of archive.photoFiles){const bytes=await readPhoto('source',f.id);assert.equal(sha(bytes),f.sha256);const prepared=await photo('destination','admin',{action:'restore',photoId:f.id});assert.equal(prepared.ok,true,'Prepare recovered file');assert.equal(prepared.data.path,f.path);const up=await request('destination','/storage/v1/object/tallerflow-photos/'+f.path,'admin',undefined,{bytes});assert.equal(up.ok,true,'Upload restored original');assert.equal((await photo('destination','admin',{action:'verify',photoId:f.id})).ok,true);assert.equal(sha(await readPhoto('destination',f.id)),f.sha256);}proof.photosRecovered=archive.photoFiles.length;});
 await check('Restored documents, operations, CSV, quotes, payments, inventory, diagnosis and module histories retain their exact originals',async()=>{const a=await rpc('destination','admin','export_workshop',{workshop_id:cfg.workshop,device_id:dev('destination','admin')});for(const k of ['documents','orders','operations','catalog','vehicle_profiles','planning_state','maintenance_state','fleet_state','case_library','inventory_state','command_receipts']){assert.deepEqual([...a.tables[k]].sort((a,b)=>String(a.id??a.workshop_id).localeCompare(String(b.id??b.workshop_id))),[...archive.tables[k]].sort((a,b)=>String(a.id??a.workshop_id).localeCompare(String(b.id??b.workshop_id))),k);}for(const original of archive.tables.clients)assert.deepEqual(a.tables.clients.find(x=>x.id===original.id),original,'Original client');const extra=a.tables.clients.filter(x=>!archive.tables.clients.some(y=>y.id===x.id));const missingOwners=[...new Set(archive.tables.vehicle_profiles.map(x=>x.owner_id))].filter(id=>!archive.tables.clients.some(x=>x.id===id));assert.deepEqual(extra.map(x=>x.id).sort(),missingOwners.sort(),'Legacy owner identity reconstruction');for(const row of extra){const source=archive.tables.vehicle_profiles.find(x=>x.owner_id===row.id);assert.equal(row.code,null);assert.equal(row.data.name,source.owner_data.name);assert.equal(row.data.phone,source.owner_data.phone??'');}proof.reconstructedLegacyClients=extra.length;for(const x of archive.tables.audit)assert.ok(a.tables.audit.some(y=>y.source_id===(x.source_id??x.id)&&y.kind===x.kind&&y.actor_id===x.actor_id));assert.ok(a.tables.audit.some(x=>x.kind==='restore_workshop'));assert.ok(a.photoFiles.every(x=>x.filePresent));proof.documentTotalCents=a.tables.documents.find(x=>x.order_id===cfg.orderId).snapshot.totalCents;assert.equal(proof.documentTotalCents,3300);});
 await check('An unrelated identity and signed-out operator cannot access the restored workshop',async()=>{await snap('destination','tech1');await rpc('destination','outsider','device_snapshot',{workshop_id:cfg.workshop,device_id:dev('destination','outsider')},true);const r=await request('destination','/auth/v1/logout?scope=local','tech1');assert.equal(r.ok,true);await rpc('destination','tech1','device_snapshot',{workshop_id:cfg.workshop,device_id:dev('destination','tech1')},true);assert.equal((await photo('destination','tech1',{action:'read',photoId:cfg.photoId})).ok,false);});
 proof.passed=true;
}catch(e){proof.error=e.message;console.error(e.message);process.exitCode=1;}finally{for(const p of ['source','destination'])for(const who of Object.keys(clients[p]))await request(p,'/auth/v1/logout?scope=local',who).catch(()=>{});await writeFile(evidence,JSON.stringify({...proof,totalChecks:checks.length},null,2));}
