// Explicitly approved isolated fixtures only; no administrative API key accepted.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const cfg=JSON.parse(await readFile(process.env.TF_QA_CONFIG,'utf8'));
if(!cfg.approved||!Object.values(cfg.users).every(u=>u.email.endsWith('@example.invalid')))throw Error('Approved fictional fixture required');
cfg.fiscalChecks??=[];
const sha=x=>createHash('sha256').update(x).digest('hex'),clients={},checks=[...cfg.fiscalChecks];
const proof={date:new Date().toISOString(),runId:cfg.runId,workshop:cfg.workshop,environment:'Real GoTrue Auth and overlapping PostgREST HTTP requests; fictional accounts',checks,passed:false,nativeValidated:false,physicalDeviceValidated:false,officialFiscalAcceptanceValidated:false,fiscalEmissionEnabled:false,fiscalTransmissionEnabled:false};
const evidence=process.env.TF_QA_EVIDENCE;
cfg.fiscalFixture??={installation:'http-'+cfg.runId,prefix:'ENSAYO-HTTP',firstId:randomUUID(),lineId:randomUUID()};
const f=cfg.fiscalFixture;await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));
async function request(path,who,body,method='POST'){
 const h={apikey:cfg.publishableKey,'Content-Type':'application/json'};if(who)h.Authorization='Bearer '+clients[who];
 const r=await fetch(cfg.url+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(45000)});let data={};try{data=await r.json()}catch{}return{ok:r.ok,status:r.status,data};
}
async function rpc(who,name,body,deny=false){const r=await request('/rest/v1/rpc/'+name,who,body);if(deny){assert.equal(r.ok,false,'Expected denial '+name);return r;}if(!r.ok)throw Error(name+': '+(r.data.message??r.status));return r.data;}
const dev=who=>cfg.users[who].device;
const read=()=>rpc('admin','fiscal_drafts',{workshop_id:cfg.workshop,device_id:dev('admin')});
const cmd=(action,payload,id=randomUUID(),who='admin',deny=false)=>rpc(who,'fiscal_draft_command',{workshop_id:cfg.workshop,device_id:dev(who),command_id:id,action,payload},deny);
async function payload(){const h=(await read()).heads.find(x=>x.issuer_nif==='B12345678'&&x.installation===f.installation);return{issuerNif:'B12345678',installation:f.installation,prefix:f.prefix,expectedSequence:h?.last_sequence??0,expectedHash:h?.last_hash??'',reason:'Fictional HTTP sandbox draft',issueDate:'2026-10-07',recipient:{name:'Fictional recipient',nif:'12345678Z'},lines:[{id:f.lineId,description:'Fictional part',unitCents:3333,quantityMilli:1500,discountBps:1250,taxBps:2100,tax:'iva',treatment:'taxable'}]};}
async function check(name,fn){if(checks.includes(name)&&!name.startsWith('Five isolated')){console.log('RETAINED '+name);return;}await fn();if(!checks.includes(name))checks.push(name);cfg.fiscalChecks=[...checks];await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));console.log('PASS '+name);await writeFile(evidence,JSON.stringify({...proof,totalChecks:checks.length},null,2)+'\n');}
try{
 await check('Five isolated identities authenticate with real GoTrue sessions',async()=>{for(const [who,u]of Object.entries(cfg.users)){const r=await request('/auth/v1/token?grant_type=password',null,{email:u.email,password:'Qa!2026'+sha(cfg.capability+u.id+cfg.url)});assert.ok(r.ok,'Fictional login '+who);assert.equal(r.data.user.id,u.id);clients[who]=r.data.access_token;await rpc(who,'device_snapshot',{workshop_id:who==='outsider'?cfg.otherWorkshop:cfg.workshop,device_id:dev(who)});}});
 await check('An administrator configures a non-emitting fictional common-territory profile',async()=>{const s=await rpc('admin','device_snapshot',{workshop_id:cfg.workshop,device_id:dev('admin')});await rpc('admin','management_command',{workshop_id:cfg.workshop,device_id:dev('admin'),command_id:randomUUID(),action:'fiscal_profile_save',payload:{revision:s.managementRevision,reason:'Fictional HTTP draft validation',profile:{country:'ES',legalForm:'company',territory:'common',sii:'no',clients:'mixed',turnover:'under_8m',taxSystem:'iva'}}});});
 await check('Append calculates 5294 cents and stores the original sandbox body',async()=>{f.firstPayload??=await payload();await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));f.first=await cmd('fiscal_draft_append',f.firstPayload,f.firstId);await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));assert.equal(f.first.number,1);assert.equal(f.first.sequence,1);assert.equal(f.first.emissionEnabled,false);assert.equal(f.first.transmissionEnabled,false);const r=(await read()).records.find(x=>x.id===f.firstId);assert.equal(r.body.calculation.totalCents,5294);assert.equal(r.body.scope,'sandbox');});
 await check('A lost reply reuses the exact command identity and number',async()=>{assert.deepEqual(await cmd('fiscal_draft_append',f.firstPayload,f.firstId),f.first);assert.equal((await read()).records.length,1);});
 await check('Changing an existing identity or using a stale chain is rejected',async()=>{await cmd('fiscal_draft_append',{...f.firstPayload,reason:'Changed'},f.firstId,'admin',true);await cmd('fiscal_draft_append',f.firstPayload,randomUUID(),'admin',true);assert.equal((await read()).records.length,1);});
 await check('Two overlapping HTTP transactions for one head commit exactly one new number',async()=>{const p=await payload();const results=await Promise.allSettled([cmd('fiscal_draft_append',p),cmd('fiscal_draft_append',p)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/chain conflict/);const s=await read();assert.equal(s.records.length,2);assert.equal(s.series[0].last_number,2);proof.overlappingHttpRequests=2;proof.distinctBackendProcessIdsObserved=false;});
 await check('Overlapping retries of one identity have only one effect',async()=>{const p=await payload(),id=randomUUID();const r=await Promise.all([cmd('fiscal_draft_append',p,id),cmd('fiscal_draft_append',p,id)]);assert.deepEqual(r[0],r[1]);assert.equal(r[0].number,3);assert.equal((await read()).records.length,3);});
 await check('Malformed data or attempted activation leaves counters and original records unchanged',async()=>{const p=await payload(),before=await read();await cmd('fiscal_draft_append',{...p,emissionEnabled:true},randomUUID(),'admin',true);await cmd('fiscal_draft_append',{...p,lines:[]},randomUUID(),'admin',true);assert.deepEqual(await read(),before);});
 await check('Withdrawal preserves the original and never reuses its number',async()=>{const original=(await read()).records.find(x=>x.id===f.firstId);const p=await payload();for(const k of ['prefix','lines','recipient','issueDate'])delete p[k];p.targetId=f.firstId;const id=randomUUID(),r=await cmd('fiscal_draft_withdraw',p,id);assert.equal(r.number,1);assert.deepEqual(await cmd('fiscal_draft_withdraw',p,id),r);assert.deepEqual((await read()).records.find(x=>x.id===f.firstId),original);await cmd('fiscal_draft_withdraw',{...p,expectedSequence:r.sequence,expectedHash:r.ledgerHash},randomUUID(),'admin',true);f.withdrawalId=id;await writeFile(process.env.TF_QA_CONFIG,JSON.stringify(cfg));});
 await check('Office and operators cannot read or append administrative drafts',async()=>{for(const who of ['office','tech1','tech2']){await rpc(who,'fiscal_drafts',{workshop_id:cfg.workshop,device_id:dev(who)},true);await cmd('fiscal_draft_append',f.firstPayload,randomUUID(),who,true);}});
 await check('Another workshop, anonymous access and direct table reads are denied',async()=>{await rpc('outsider','fiscal_drafts',{workshop_id:cfg.workshop,device_id:dev('outsider')},true);await rpc(null,'fiscal_drafts',{workshop_id:cfg.workshop,device_id:dev('admin')},true);assert.equal((await request('/rest/v1/fiscal_draft_records?select=*','admin',undefined,'GET')).ok,false);});
 await check('Format 14 exports sandbox chains, records, receipts and audit without sessions',async()=>{const a=await rpc('admin','export_workshop',{workshop_id:cfg.workshop,device_id:dev('admin')});assert.equal(a.databaseVersion,14);assert.equal(a.tables.fiscal_draft_records.length,4);assert.equal(a.tables.fiscal_draft_series[0].last_number,3);assert.equal(a.tables.fiscal_draft_heads[0].last_sequence,4);for(const id of [f.firstId,f.withdrawalId]){assert.ok(a.tables.command_receipts.some(x=>x.id===id));assert.ok(a.tables.audit.some(x=>x.operation_id===id));}assert.equal(JSON.stringify(a).includes(clients.admin),false);proof.databaseArchiveVersion=14;proof.recordsExported=a.tables.fiscal_draft_records.length;});
 await check('Logout revokes ledger reads and idempotent retries before JWT expiry',async()=>{assert.ok((await request('/auth/v1/logout?scope=local','admin')).ok);await rpc('admin','fiscal_drafts',{workshop_id:cfg.workshop,device_id:dev('admin')},true);await cmd('fiscal_draft_append',f.firstPayload,f.firstId,'admin',true);});
 proof.passed=true;
}catch(e){proof.error=e.message;console.error(e.message);process.exitCode=1;}
finally{for(const who of Object.keys(clients))await request('/auth/v1/logout?scope=local',who).catch(()=>{});await writeFile(evidence,JSON.stringify({...proof,totalChecks:checks.length},null,2)+'\n');console.log(JSON.stringify({passed:proof.passed,totalChecks:checks.length}));}
