// Two isolated workshops and fictional Auth accounts only. No privileged key.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const cfgPath=process.env.TF_RECOVERY_CONFIG;
if(!cfgPath)throw new Error('Approved isolated recovery configuration required');
const cfg=JSON.parse(await readFile(cfgPath,'utf8'));
if(cfg.approved!==true||cfg.source===cfg.destination||!Object.values(cfg.users).every(u=>u.email.endsWith('@example.invalid')))throw new Error('Fictional fixture approval required');
const sha=b=>createHash('sha256').update(b).digest('hex');
const save=()=>writeFile(cfgPath,JSON.stringify(cfg),{mode:0o600});
for(const k of ['orderId','taskId','photoId','prepareId','inspectionId','inspectionRow','restoreId'])cfg[k]??=randomUUID();
cfg.devices??={source:Object.fromEntries(Object.entries(cfg.users).map(([r,u])=>[r,u.device])),destination:{admin:randomUUID(),tech:randomUUID()}};
cfg.clients??={source:{},destination:{}};await save();
const checks=[],evidence=process.env.TF_RECOVERY_EVIDENCE??'outputs/TallerFlow/evidence/hosted-recovery-validation.json';
const proof={date:new Date().toISOString(),runId:cfg.runId,source:cfg.source,destination:cfg.destination,workshop:cfg.workshop,fictionalAccounts:true,environment:'Two hosted Supabase projects; GoTrue, PostgREST, Edge and Storage HTTP',nativeValidated:false,checks,passed:false};
async function request(project,path,{who,body,method='POST',bytes,jwt}={}){
 const p=cfg.projects[project],headers={apikey:p.anon};if(who||jwt)headers.Authorization='Bearer '+(jwt??cfg.clients[project][who].access_token);
 headers['Content-Type']=bytes?'image/jpeg':'application/json';if(bytes)headers['cache-control']='max-age=0';
 const r=await fetch(p.url+path,{method,headers,body:bytes??(body===undefined?undefined:JSON.stringify(body)),signal:AbortSignal.timeout(45000)});
 const text=await r.text();let data={};try{data=JSON.parse(text);}catch{}return {ok:r.ok,status:r.status,data};
}
async function rpc(project,who,name,body,deny=false){const r=await request(project,'/rest/v1/rpc/'+name,{who,body});if(deny){assert.equal(r.ok,false,'Expected denial '+name);return r;}if(!r.ok)throw new Error(name+' '+r.status+' '+(r.data.message??r.data.error??''));return r.data;}
const snap=(p,who,d=cfg.devices[p][who])=>rpc(p,who,'device_snapshot',{workshop_id:cfg.workshop,device_id:d});
const command=(p,who,action,payload,id=randomUUID())=>rpc(p,who,'reliability_command',{workshop_id:cfg.workshop,device_id:cfg.devices[p][who],command_id:id,action,payload});
async function operation(who,kind,payload,at){const s=await snap('source',who),record={id:randomUUID(),orderId:cfg.orderId,actorId:cfg.users[who].id,kind,baseRevision:s.orders.find(o=>o.id===cfg.orderId)?.revision??0,at:at??new Date().toISOString(),payload};const result=await rpc('source',who,'apply_operation',{workshop_id:cfg.workshop,device_id:cfg.devices.source[who],operation:record});assert.equal(result.status,'accepted',String(result.reason??kind));return {record,result};}
const photo=(p,who,body)=>request(p,'/functions/v1/workshop-photos',{who,body:{...body,workshopId:cfg.workshop,deviceId:cfg.devices[p][who]}});
async function bytes(p,who){const r=await fetch(cfg.projects[p].url+'/functions/v1/workshop-photos',{method:'POST',headers:{apikey:cfg.projects[p].anon,Authorization:'Bearer '+cfg.clients[p][who].access_token,'Content-Type':'application/json'},body:JSON.stringify({action:'read',workshopId:cfg.workshop,deviceId:cfg.devices[p][who],photoId:cfg.photoId}),signal:AbortSignal.timeout(45000)});return {ok:r.ok,status:r.status,data:Buffer.from(await r.arrayBuffer()),cache:r.headers.get('cache-control')};}
async function check(name,f){await f();checks.push(name);console.log('PASS '+name);await writeFile(evidence,JSON.stringify(proof,null,2)+'\n');}
const jpeg=await readFile(process.env.TF_QA_JPEG??'work/qa-fictional.jpg');
try{
 await check('Original Auth UUIDs sign in to both projects using distinct new passwords',async()=>{for(const project of ['source','destination'])for(const [role,u]of Object.entries(cfg.users)){if(!cfg.clients[project][role]){const p=cfg.projects[project],password='Qa!2026'+sha(cfg.capability+u.id+p.url);const r=await request(project,'/auth/v1/token?grant_type=password',{body:{email:u.email,password}});assert.equal(r.ok,true,'Login '+project+' '+role);assert.equal(r.data.user.id,u.id);cfg.clients[project][role]=r.data;await save();}assert.equal(cfg.clients[project][role].user.id,u.id);}assert.notEqual(cfg.clients.source.admin.access_token,cfg.clients.destination.admin.access_token);});
 await check('A source token cannot authenticate against the recovery project',async()=>{assert.equal((await request('destination','/auth/v1/user',{method:'GET',jwt:cfg.clients.source.admin.access_token})).ok,false);});
 await check('Source work includes two inspection versions, original photo, time and immutable note',async()=>{
  let s=await snap('source','admin');await snap('source','tech');for(const d of s.devices.filter(d=>!d.retiredAt&&!Object.values(cfg.devices.source).includes(d.id)))await command('source','admin','retire_device',{deviceId:d.id,reason:'Prior fictional test session retired; originals retained'});s=await snap('source','admin');if(s.orders.find(o=>o.id===cfg.orderId)?.document)return;
  if(!s.orders.find(o=>o.id===cfg.orderId)){
   await rpc('source','admin','management_command',{workshop_id:cfg.workshop,device_id:cfg.devices.source.admin,command_id:randomUUID(),action:'settings_save',payload:{revision:s.managementRevision,reason:'Fictional recovery validation',settings:{hourlyRateCents:6000,taxBps:1000,internalHourlyCostCents:2500,internalCostKnown:true}}});
   await operation('admin','receive',{plate:'9902FIC',country:'ES',vin:'RECOVERY-'+cfg.orderId,vehicle:'Fictional recovery vehicle',engine:'Test',client:'Fictional owner',phone:'',km:100,symptom:'Fictional original symptom',tasks:[{id:cfg.taskId,title:'Fictional test task',estimateMinutes:30,assignees:[cfg.users.tech.id]}]});
   await operation('admin','authorize',{taskId:cfg.taskId,approvedCents:100000,version:1,customer:'Fictional owner',evidence:'Fictional authorization'});
  }
  s=await snap('source','tech');if(!s.photoManifest.find(p=>p.id===cfg.photoId)){
   const r=await photo('source','tech',{action:'prepare',commandId:cfg.prepareId,payload:{id:cfg.photoId,orderId:cfg.orderId,originalDeviceId:cfg.devices.source.tech,sha256:sha(jpeg),size:jpeg.length,mime:'image/jpeg',caption:'Fictional original photo',capturedAt:new Date().toISOString()}});assert.equal(r.ok,true,'Photo prepare');const up=await request('source','/storage/v1/object/tallerflow-photos/'+r.data.path,{who:'tech',bytes:jpeg});assert.equal(up.ok,true,'Upload source');assert.equal((await photo('source','tech',{action:'verify',photoId:cfg.photoId})).ok,true,'Verify source');
  }
  s=await snap('source','tech');let o=s.orders.find(o=>o.id===cfg.orderId);let version=o.inspections?.find(i=>i.id===cfg.inspectionId)?.version??0;
  if(version===0){await operation('tech','inspection_save',{id:cfg.inspectionId,expectedVersion:0,title:'Fictional check',reason:'First measurement',items:[{id:cfg.inspectionRow,label:'Brakes',status:'attention',observation:'Fictional observation',photoIds:[cfg.photoId]}]});version=1;}
  if(version===1)await operation('tech','inspection_save',{id:cfg.inspectionId,expectedVersion:1,title:'Fictional check',reason:'Repeated measurement',items:[{id:cfg.inspectionRow,label:'Brakes',status:'correct',observation:'Fictional corrected result',photoIds:[cfg.photoId]}]});
  o=(await snap('source','tech')).orders.find(o=>o.id===cfg.orderId);if(o.times.length===0){const start=await operation('tech','start',{taskId:cfg.taskId},new Date(Date.now()-60000).toISOString());await operation('tech','stop',{sessionId:start.record.id});}
  o=(await snap('source','tech')).orders.find(o=>o.id===cfg.orderId);if(!o.tasks[0].done)await operation('tech','finish_task',{taskId:cfg.taskId});
  s=await snap('source','admin');for(const incident of s.incidents.filter(i=>!i.resolution))await command('source','admin','resolve',{operationId:incident.operation.id,revision:s.orders.find(o=>o.id===cfg.orderId).revision,outcome:'archive',reason:'Rejected fictional test command retained after correcting the test'});await operation('admin','billable',{taskId:cfg.taskId,minutes:30,reason:'Fictional review'});await operation('admin','quality',{result:'Fictional final quality',pendingSymptoms:''});
  o=(await snap('source','admin')).orders.find(o=>o.id===cfg.orderId);const close=await command('source','admin','request_close',{orderId:cfg.orderId,revision:o.revision,exceptionReason:'Prior fictional sessions revoked; all original records and stopped timers verified',retiredDevices:s.devices.filter(d=>d.retiredAt).map(d=>d.id)});const ack={orderId:cfg.orderId,revision:o.revision,requestId:close.requestId,locallyFrozen:true};for(const who of ['admin','tech'])await command('source',who,'ack_close',ack);const issued=await command('source','admin','issue',{orderId:cfg.orderId,requestId:close.requestId});assert.equal(issued.document.totalCents,3300);
 });
 await check('Complete export excludes Auth and preserves documents, photos, inspection history and audit',async()=>{cfg.archive??=await rpc('source','admin','export_workshop',{workshop_id:cfg.workshop,device_id:cfg.devices.source.admin});await save();const a=cfg.archive;assert.equal(a.authExcluded,true);assert.equal(a.databaseVersion,13);assert.equal(a.tables.documents.length,1);assert.equal(a.photoFiles[0].filePresent,true);assert.equal(a.tables.orders[0].data.inspectionHistory.length,1);assert.ok(a.tables.audit.length>=8);assert.equal(JSON.stringify(a).includes(cfg.clients.source.admin.access_token),false);assert.equal(sha((await bytes('source','admin')).data),sha(jpeg));});
 await check('Recovery restores original rows once under a new authenticated device',async()=>{await snap('destination','admin');const body={workshop_id:cfg.workshop,device_id:cfg.devices.destination.admin,restore_id:cfg.restoreId,archive:cfg.archive};const result=await rpc('destination','admin','restore_workshop',body);assert.equal(result.restored,true);assert.deepEqual(await rpc('destination','admin','restore_workshop',body),result);const changed={...cfg.archive,exportedAt:new Date().toISOString()};await rpc('destination','admin','restore_workshop',{...body,archive:changed},true);});
 await check('Historical devices and old acknowledgements never become active authority',async()=>{for(const who of ['admin','tech'])await rpc('destination',who,'device_snapshot',{workshop_id:cfg.workshop,device_id:cfg.devices.source[who]},true);await snap('destination','tech');const s=await snap('destination','admin');assert.ok(s.devices.filter(d=>Object.values(cfg.devices.source).includes(d.id)).every(d=>d.retiredAt));});
 await check('Recording work is blocked while recovered photo originals are missing',async()=>{const denied=await rpc('destination','admin','apply_operation',{workshop_id:cfg.workshop,device_id:cfg.devices.destination.admin,operation:{id:randomUUID(),orderId:randomUUID(),actorId:cfg.users.admin.id,kind:'receive',baseRevision:0,at:new Date().toISOString(),payload:{}}},true);assert.match(denied.data.message,/Restore original photo files/);});
 await check('Photo restoration preserves immutable path, bytes, hash and current permissions',async()=>{const r=await photo('destination','admin',{action:'restore',photoId:cfg.photoId});assert.equal(r.ok,true,'Prepare restore');assert.equal(r.data.path,cfg.archive.photoFiles[0].path);const up=await request('destination','/storage/v1/object/tallerflow-photos/'+r.data.path,{who:'admin',bytes:jpeg});if(!up.ok)assert.equal(sha((await bytes('destination','admin')).data),sha(jpeg));assert.equal((await photo('destination','admin',{action:'verify',photoId:cfg.photoId})).ok,true);for(const who of ['admin','tech']){const b=await bytes('destination',who);assert.equal(b.ok,true);assert.equal(sha(b.data),sha(jpeg));assert.ok(b.cache.includes('no-store'));}assert.equal((await request('destination','/storage/v1/object/authenticated/tallerflow-photos/'+r.data.path,{who:'admin',method:'GET'})).ok,false);});
 await check('Recovered export keeps the exact document, operation identities, technical versions and audit originals',async()=>{const a=await rpc('destination','admin','export_workshop',{workshop_id:cfg.workshop,device_id:cfg.devices.destination.admin});assert.deepEqual(a.tables.documents,cfg.archive.tables.documents);assert.deepEqual(a.tables.orders,cfg.archive.tables.orders);assert.deepEqual(a.tables.operations,cfg.archive.tables.operations);assert.deepEqual(a.tables.catalog,cfg.archive.tables.catalog);for(const row of cfg.archive.tables.audit)assert.ok(a.tables.audit.find(x=>x.source_id===(row.source_id??row.id)&&x.kind===row.kind&&x.actor_id===row.actor_id));assert.equal(a.photoFiles[0].filePresent,true);assert.ok(a.tables.audit.find(x=>x.kind==='restore_workshop'));proof.documentTotalCents=a.tables.documents[0].snapshot.totalCents;assert.equal(proof.documentTotalCents,3300);proof.photoHash=sha(jpeg);proof.originalOperationCount=a.tables.operations.length;});
 await check('Sign-out revokes fresh RPC and private photo reads in the recovered project',async()=>{assert.equal((await request('destination','/auth/v1/logout?scope=local',{who:'tech'})).ok,true);await rpc('destination','tech','device_snapshot',{workshop_id:cfg.workshop,device_id:cfg.devices.destination.tech},true);assert.equal((await bytes('destination','tech')).ok,false);});
 proof.passed=true;proof.totalChecks=checks.length;
}finally{
 if(proof.passed)for(const p of ['source','destination'])for(const role of Object.keys(cfg.clients[p]))try{await request(p,'/auth/v1/logout?scope=local',{who:role});}catch{}
 await writeFile(evidence,JSON.stringify(proof,null,2)+'\n');
}
console.log(`${checks.length} hosted recovery checks passed.`);
