import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
let n=7000,passed=0;const id=()=>`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`;
const w=id(),office=id(),tech=id(),other=id(),od=id(),td=id(),xd=id(),order=id(),task=id(),inspection=id(),row=id();
const db=new PGlite();
await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");
await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1),($2),($3)',[office,tech,other]);
await db.query("insert into private.workshops(id,name) values($1,'Fictional inspection')",[w]);
await db.query("insert into private.members values($1,$2,'Office','admin',true,true),($1,$3,'Technician','technician',false,true),($1,$4,'Other','technician',false,true)",[w,office,tech,other]);
let actor,device;
async function login(u,d){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[d,u]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,session_id:d})]);await db.exec('set role authenticated');actor=u;device=d;await snap();}
const snap=async()=>(await db.query('select public.device_snapshot($1,$2) r',[w,device])).rows[0].r;
const command=async(action,p)=>(await db.query('select public.reliability_command($1,$2,$3,$4,$5) r',[w,device,id(),action,p])).rows[0].r;
async function op(kind,p,{opid=id(),revision}={}){const s=await snap();const o=s.orders.find(o=>o.id===order);const record={id:opid,orderId:order,actorId:actor,kind,at:new Date().toISOString(),baseRevision:revision??o?.revision??0,payload:p};return {record,result:(await db.query('select public.apply_operation($1,$2,$3) r',[w,device,record])).rows[0].r};}
const payload=()=>({id:inspection,expectedVersion:0,title:'Inspection',reason:'Fictional check',items:[{id:row,label:'Brakes',status:'follow_up',observation:'Measure at the next visit',photoIds:[]}]});
const test=async(name,f)=>{await f();passed++;console.log('PASS '+name);};
try{
 await login(office,od);assert.equal((await op('receive',{plate:'9901FIC',country:'ES',vin:'INSPECTION-FICTIONAL',vehicle:'Fictional',engine:'2020',client:'Fictional private owner',phone:'600000000',km:10,symptom:'Fictional symptom',tasks:[{id:task,title:'Check',assignees:[tech],estimateMinutes:30}]})).result.status,'accepted');await login(tech,td);
 let first;
 await test('An assigned operator records findings without creating tasks or charges',async()=>{const before=(await snap()).orders[0];first=await op('inspection_save',payload());assert.equal(first.result.status,'accepted');const after=(await snap()).orders[0];assert.deepEqual(after.tasks,before.tasks);assert.deepEqual(after.parts,before.parts);assert.equal(after.inspections[0].items[0].status,'follow_up');});
 await test('A lost response replays the original once',async()=>{assert.deepEqual((await db.query('select public.apply_operation($1,$2,$3) r',[w,device,first.record])).rows[0].r,first.result);await assert.rejects(()=>db.query('select public.apply_operation($1,$2,$3)',[w,device,{...first.record,payload:{...payload(),title:'Changed'}}]),/Idempotency/);assert.equal((await snap()).orders[0].inspections.length,1);});
 await test('Review keeps its previous version in private technical history',async()=>{const before=(await snap()).orders[0].inspections[0];const p=payload();p.expectedVersion=1;p.reason='Repeated measurement';p.items[0].status='attention';await login(office,od);assert.equal((await op('inspection_save',p)).result.status,'accepted');await login(tech,td);const s=await snap();assert.deepEqual(s.orders[0].inspectionHistory,[before]);assert.equal(s.vehicleHistory[0].inspections[0].version,2);assert.equal(s.vehicleHistory[0].recipient,undefined);});
 await test('Concurrent stale revision and obsolete version retain conflict evidence',async()=>{assert.equal((await op('inspection_save',{...payload(),expectedVersion:2},{revision:0})).result.status,'conflict');assert.equal((await op('inspection_save',payload())).result.status,'conflict');assert.equal((await snap()).orders[0].inspections[0].version,2);});
 await test('Invalid findings, duplicates, money injection and unrelated photos are rejected',async()=>{const cases=[{...payload(),priceCents:1},{...payload(),items:[]},{...payload(),items:[...payload().items,...payload().items]}, {...payload(),items:[{...payload().items[0],status:'authorized'}]},{...payload(),items:[{...payload().items[0],observation:''}]},{...payload(),items:[{...payload().items[0],photoIds:[id()]}]},{...payload(),items:[{...payload().items[0],priceCents:1}]}];for(const p of cases)assert.equal((await op('inspection_save',{...p,expectedVersion:2})).result.status,'conflict');assert.equal((await snap()).orders[0].inspections[0].version,2);});
 await test('Unassigned and revoked accounts cannot inspect an order',async()=>{await login(other,xd);await assert.rejects(()=>op('inspection_save',payload()),/not enrolled/);await login(tech,td);await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[td]);await db.exec('set role authenticated');await assert.rejects(()=>snap(),/session/i);await login(tech,td);});
 await test('Resolved conflicts permit coordinated closure and late inspections preserve the document',async()=>{await login(office,od);let s=await snap();for(const i of s.incidents.filter(i=>!i.resolution))await command('resolve',{operationId:i.operation.id,revision:s.orders[0].revision,outcome:'archive',reason:'Fictional rejected inspection retained'});assert.equal((await op('quality',{result:'Fictional final check',pendingSymptoms:''})).result.status,'accepted');s=await snap();const revision=s.orders[0].revision;const close=await command('request_close',{orderId:order,revision});const ack={orderId:order,revision,requestId:close.requestId,locallyFrozen:true};await command('ack_close',ack);await login(tech,td);await command('ack_close',ack);await login(office,od);const issued=await command('issue',{orderId:order,requestId:close.requestId});assert.equal(issued.document.totalCents,0);const before=(await snap()).orders[0].inspections;assert.equal((await op('inspection_save',{...payload(),expectedVersion:2})).result.status,'late');assert.deepEqual((await snap()).orders[0].inspections,before);});
 await test('Complete export keeps versions, originals, immutable document and audit',async()=>{const archive=(await db.query('select public.export_workshop($1,$2) r',[w,od])).rows[0].r;assert.equal(archive.tables.orders[0].data.inspections[0].version,2);assert.equal(archive.tables.orders[0].data.inspectionHistory.length,1);assert.ok(archive.tables.operations.find(o=>o.id===first.record.id));assert.equal(archive.tables.audit.filter(a=>a.kind==='inspection_save').length,2);assert.equal(archive.tables.documents.length,1);});
 console.log(`${passed} inspection checks passed in PostgreSQL/PGlite with synthetic Auth.`);
}finally{await db.close();}
