import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
let seq=12000,passed=0;const id=()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,'0')}`;
const w=id(),admin=id(),tech=id(),ad=id(),td=id(),source=id(),target=id();
const db=new PGlite();
await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");
await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL(`../supabase/migrations/${f}`,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1),($2)',[admin,tech]);await db.query("insert into private.workshops(id,name) values($1,'Fictional return validation')",[w]);await db.query("insert into private.members values($1,$2,'Fictional admin','admin',true,true),($1,$3,'Fictional tech','technician',false,true)",[w,admin,tech]);
let actor=admin,dev=ad;
const snap=async()=>(await db.query('select public.device_snapshot($1,$2) r',[w,dev])).rows[0].r;
async function login(user,device){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[device,user]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,session_id:device})]);await db.exec('set role authenticated');actor=user;dev=device;await snap();}
const draft=()=>({plate:'9010FIC',country:'ES',vin:'FICTIONAL-RETURNS',vehicle:'Fictional car',engine:'2020',client:'Fictional owner',phone:'',km:100,symptom:'New original symptom',tasks:[{id:id(),title:'New diagnosis',estimateMinutes:30,assignees:[tech]}]});
async function op(kind,oid,p,rev,opid=id()){const record={id:opid,orderId:oid,actorId:actor,kind,baseRevision:rev??(await snap()).orders.find(o=>o.id===oid)?.revision??0,at:new Date().toISOString(),payload:p};return {record,result:(await db.query('select public.apply_operation($1,$2,$3) r',[w,dev,record])).rows[0].r};}
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
try{
 await login(admin,ad);assert.equal((await op('receive',source,draft())).result.status,'accepted');await db.exec('reset role');await db.query("update private.orders set data=data||$1 where workshop_id=$2 and id=$3",[{document:{totalCents:12345,clientSnapshot:'Original recipient'},status:'delivered'},w,source]);await login(admin,ad);
 const original=(await snap()).orders.find(o=>o.id===source),link={sourceOrderId:source,classification:'warranty',reason:'Fictional office classification'};let first,change;
 await test('Linked reception retains source note and requires fresh authorization',async()=>{first=await op('receive',target,{...draft(),returnLink:link});assert.equal(first.result.status,'accepted');const s=await snap(),o=s.orders.find(o=>o.id===target);assert.deepEqual(s.orders.find(o=>o.id===source),original);assert.equal(o.returnHistory[0].classification,'warranty');assert.equal(o.tasks[0].authorized,false);assert.equal(o.tasks[0].approvedCents,0);assert.equal(o.document,undefined);});
 await test('Lost response preserves one link and one set of fresh tasks',async()=>{assert.deepEqual((await db.query('select public.apply_operation($1,$2,$3) r',[w,dev,first.record])).rows[0].r,first.result);assert.equal((await snap()).orders.find(o=>o.id===target).returnHistory.length,1);});
 await test('Human reclassification appends history and retry is once',async()=>{change=await op('return_classify',target,{...link,classification:'different',reason:'Fictional measurement identifies different fault'});assert.equal(change.result.status,'accepted');assert.deepEqual((await db.query('select public.apply_operation($1,$2,$3) r',[w,dev,change.record])).rows[0].r,change.result);const h=(await snap()).orders.find(o=>o.id===target).returnHistory;assert.equal(h.length,2);assert.equal(h[0].classification,'warranty');assert.equal(h[1].classification,'different');});
 await test('Stale reclassification and replacement of original reference retain conflicts',async()=>{assert.equal((await op('return_classify',target,link,0)).result.status,'conflict');assert.equal((await op('return_classify',target,{...link,sourceOrderId:id()})).result.status,'conflict');assert.equal((await snap()).orders.find(o=>o.id===target).returnHistory.length,2);});
 await test('Foreign vehicle or unknown source rolls back reception atomically',async()=>{for(const p of [{...draft(),plate:'9020FIC',vin:'OTHER-VEHICLE',returnLink:link},{...draft(),returnLink:{...link,sourceOrderId:id()}}]){const oid=id();assert.equal((await op('receive',oid,p)).result.status,'conflict');assert.equal((await snap()).orders.some(o=>o.id===oid),false);}});
 await test('Operators cannot classify or read personal classification evidence',async()=>{await login(tech,td);assert.equal((await snap()).orders.find(o=>o.id===target).returnHistory,undefined);assert.equal((await op('return_classify',target,link,1)).result.status,'conflict');await assert.rejects(()=>db.query('select private.return_classification($1,$2,now())',[link,tech]),/permission denied/);await login(admin,ad);});
 await test('Ownership change gives the new return its current recipient without copying old documents',async()=>{const v=(await snap()).vehicleProfiles[0],owner=id();await db.query("select public.vehicle_command($1,$2,$3,'vehicle_change',$4)",[w,dev,id(),{vehicleId:v.id,revision:v.revision,change:'owner',ownerId:owner,name:'New fictional owner',phone:'',reason:'Fictional ownership checked'}]);const oid=id();assert.equal((await op('receive',oid,{...draft(),client:'New fictional owner',returnLink:link})).result.status,'accepted');const s=await snap(),o=s.orders.find(o=>o.id===oid);assert.equal(o.ownerId,owner);assert.equal(o.document,undefined);assert.deepEqual(s.orders.find(o=>o.id===source).document,original.document);});
 await test('Complete backup retains new link, classification history, original document and audit',async()=>{const a=(await db.query('select public.export_workshop($1,$2) r',[w,dev])).rows[0].r;assert.equal(a.tables.orders.find(o=>o.id===target).data.returnHistory.length,2);assert.deepEqual(a.tables.orders.find(o=>o.id===source).data.document,original.document);assert.equal(a.tables.audit.filter(x=>x.kind==='return_classify').length,1);});
 console.log(`${passed} linked-return checks passed in PostgreSQL/PGlite with synthetic Auth.`);
}finally{await db.close();}
