import {PGlite} from '@electric-sql/pglite';import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
let seq=21000,passed=0;const id=()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,'0')}`;
const w=id(),other=id(),admin=id(),a=id(),b=id(),dev=id(),td=id(),oid=id(),otherOrder=id(),task=id(),pid=id();const db=new PGlite();
await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort())await db.exec(await readFile(new URL(`../supabase/migrations/${f}`,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1),($2),($3)',[admin,a,b]);await db.query("insert into private.workshops(id,name) values($1,'Fictional maintenance'),($2,'Isolated workshop')",[w,other]);await db.query("insert into private.members values($1,$2,'Admin','admin',true,true),($1,$3,'Tech','technician',false,true),($1,$4,'Other tech','technician',false,true),($5,$2,'Admin','admin',true,true)",[w,admin,a,b,other]);
let device=dev;async function login(user,dd){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[dd,user]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,session_id:dd})]);await db.exec('set role authenticated');device=dd;await snap();}
const snap=async()=>(await db.query('select public.device_snapshot($1,$2) r',[w,device])).rows[0].r;
const command=async(action,p,cid=id())=>(await db.query('select public.maintenance_command($1,$2,$3,$4,$5) r',[w,device,cid,action,p])).rows[0].r;
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};let vehicle;
const plan=async(overrides={})=>({id:pid,revision:(await snap()).maintenance.revision,vehicleId:vehicle,title:'Fictional oil check',source:'Manual criterion checked by office',zone:'Europe/Madrid',dueDate:'2026-10-08',dueKm:130000,intervalMonths:1,intervalKm:15000,reason:'Fictional maintenance plan',...overrides});
const complete=async(overrides={})=>({id:pid,revision:(await snap()).maintenance.revision,performedAt:'2026-09-30T22:30:00Z',km:129000,orderId:oid,evidence:'Fictional intervention checked',reason:'Fictional manual completion',...overrides});
try{
 await login(admin,dev);for(const [order,plate] of [[oid,'9100FIC'],[otherOrder,'9101FIC']]){const r=(await db.query('select public.apply_operation($1,$2,$3) r',[w,device,{id:id(),orderId:order,actorId:admin,kind:'receive',baseRevision:0,at:new Date().toISOString(),payload:{plate,country:'ES',vin:'FICTIONAL-'+plate,vehicle:'Fictional',engine:'2020',client:'Fictional owner',phone:'',km:128450,symptom:'Fictional',tasks:[{id:id(),title:'Diagnosis',estimateMinutes:30,assignees:[a]}]}}])).rows[0].r;assert.equal(r.status,'accepted');}vehicle=(await snap()).orders.find(o=>o.id===oid).vehicleId;
 let p,cid=id();
 await test('Office plans explicit dates, mileage and manual criteria without changing repair',async()=>{const before=(await snap()).orders;p=await plan();await command('care_plan',p,cid);assert.deepEqual((await snap()).orders,before);assert.equal((await snap()).maintenance.plans[0].source,p.source);});
 await test('Response retries cannot duplicate plans or reuse altered content',async()=>{await command('care_plan',p,cid);assert.equal((await snap()).maintenance.plans.length,1);await assert.rejects(()=>command('care_plan',{...p,title:'Changed'},cid),/ID reused/);});
 await test('Stale version, foreign vehicle, invalid calendar date and missing threshold fail atomically',async()=>{for(const overrides of [{revision:0},{vehicleId:id()},{dueDate:'2026-02-30'},{dueDate:null,dueKm:null},{dueDate:null},{zone:'Unknown/Zone'},{source:''},{intervalKm:0}])await assert.rejects(async()=>command('care_plan',await plan({...overrides,id:id()})));assert.equal((await snap()).maintenance.plans.length,1);});
 await test('Versions preserve original plan and same vehicle identity',async()=>{await command('care_plan',await plan({title:'Fictional oil and filter'}));assert.equal((await snap()).maintenance.plans[0].versions.length,2);assert.equal((await snap()).maintenance.plans[0].versions[0].title,'Fictional oil check');await assert.rejects(async()=>command('care_plan',await plan({vehicleId:(await snap()).orders.find(o=>o.id===otherOrder).vehicleId})),/original vehicle/);});
 let completion,completionId=id();
 await test('Completion uses local calendar date, recurring thresholds and highest observed mileage',async()=>{completion=await complete();const before=(await snap()).orders;await command('care_complete',completion,completionId);const s=await snap(),p=s.maintenance.plans[0];assert.equal(p.dueDate,'2026-11-01');assert.equal(p.dueKm,144000);assert.equal(p.completions[0].performedDate,'2026-10-01');assert.equal(p.completions[0].dueKm,130000);assert.equal(s.vehicleProfiles.find(v=>v.id===vehicle).km,129000);assert.deepEqual(s.orders,before);});
 await test('Lost completion reply reuses identity, while duplicate chronological and future entries fail',async()=>{await command('care_complete',completion,completionId);assert.equal((await snap()).maintenance.plans[0].completions.length,1);for(const overrides of [{},{performedAt:'2026-10-01T10:00:00Z',km:128000},{performedAt:new Date(Date.now()+86400000).toISOString()},{orderId:otherOrder},{evidence:''}])await assert.rejects(async()=>command('care_complete',await complete(overrides)));});
 await test('Month recurrence clamps January 31 and respects leap days',async()=>{const leap=id();await command('care_plan',await plan({id:leap,intervalMonths:1,intervalKm:null}));await command('care_complete',await complete({id:leap,performedAt:'2024-01-31T10:00:00Z',km:1000,orderId:null}));assert.equal((await snap()).maintenance.plans.find(p=>p.id===leap).dueDate,'2024-02-29');});
 await test('Single plan completion and pause keep evidence and cannot overwrite terminal plans',async()=>{const once=id();await command('care_plan',await plan({id:once,intervalMonths:null,intervalKm:null}));await command('care_complete',await complete({id:once}));assert.equal((await snap()).maintenance.plans.find(p=>p.id===once).status,'completed');await assert.rejects(async()=>command('care_plan',await plan({id:once})),/new plan/);await command('care_pause',{id:pid,revision:(await snap()).maintenance.revision,reason:'Fictional pause'});assert.equal((await snap()).maintenance.plans.find(p=>p.id===pid).completions.length,1);});
 await test('Assigned technicians see technical maintenance without office history; other technicians see none',async()=>{await login(a,td);let s=await snap();assert.ok(s.maintenance.plans.length);assert.deepEqual(s.maintenance.plans[0].versions,[]);assert.deepEqual(s.maintenance.plans[0].events,[]);await assert.rejects(()=>command('care_pause',{}),/Office/);await login(b,id());s=await snap();assert.equal(s.maintenance.plans.length,0);await login(admin,dev);});
 await test('Owner and plate changes retain technical plan without adding old customer documents',async()=>{await db.exec('reset role');await db.query('update private.vehicle_profiles set owner_id=$1 where workshop_id=$2 and vehicle_id=$3',[id(),w,vehicle]);await db.exec('set role authenticated');const s=await snap();assert.equal(s.maintenance.plans.find(p=>p.id===pid).vehicleId,vehicle);assert.equal(s.maintenance.plans.find(p=>p.id===pid).completions.length,1);assert.equal(s.maintenance.plans.find(p=>p.id===pid).document,undefined);});
 await test('Current archive contains maintenance, immutable versions, audit and receipts',async()=>{const ar=(await db.query('select public.export_workshop($1,$2) r',[w,dev])).rows[0].r;assert.equal(ar.databaseVersion,12);assert.deepEqual(ar.tables.maintenance_state[0].data,(await snap()).maintenance);assert.ok(ar.tables.command_receipts.find(x=>x.id===completionId));await db.exec('reset role');await db.query('select private.validate_maintenance($1,$2)',[w,ar.tables.maintenance_state[0].data]);await db.exec('set role authenticated');});
 await test('Workshop isolation, anonymous access and retired sessions are enforced',async()=>{assert.equal((await db.query('select public.workshop_snapshot($1) r',[other])).rows[0].r.maintenance.plans.length,0);await assert.rejects(()=>db.query('select * from private.maintenance_state'),/permission denied/);await db.exec('reset role;set role anon');await assert.rejects(()=>command('care_pause',{}),/permission denied/);await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[dev]);await db.exec('set role authenticated');await assert.rejects(()=>command('care_plan',p,cid),/session/);});
 console.log(`${passed} maintenance checks passed in PostgreSQL/PGlite with synthetic Auth.`);
}finally{await db.close();}
