import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {photoHandler} from '../supabase/functions/workshop-photos/handler.ts';
const uuid='01000000-0000-4000-8000-000000000001',bytes=new Uint8Array([255,216,255,0,255,217]);
const sha256=createHash('sha256').update(bytes).digest('hex');
let passed=0,buckets=0,downloads=0,finishes=0,prepares=0;
const info={id:uuid,path:`${uuid}/${uuid}/${uuid}.jpg`,sha256,size:bytes.length,userId:uuid,sessionId:uuid};
const dep={authenticate:async t=>t==='valid',prepare:async()=>{prepares++;},info:async()=>info,bucket:async()=>{buckets++;},download:async path=>{assert.equal(path,info.path);downloads++;return bytes;},finish:async(w,d,p,i,h,s)=>{assert.equal(h,sha256);assert.equal(s,bytes.length);finishes++;return {status:'attached'};}};
const body={action:'verify',workshopId:uuid,deviceId:uuid,photoId:uuid};
const req=(b=body,token='valid')=>new Request('https://example.invalid',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify(b)});
const test=async(name,f)=>{await f();passed++;console.log('PASS '+name);};
await test('Invalid authentication has no privileged Storage effects',async()=>{assert.equal((await photoHandler(dep)(req(body,'invalid'))).status,401);assert.equal(buckets+downloads+finishes,0);});
await test('User-scoped denial precedes all service-role operations',async()=>{const denied={...dep,info:async()=>{throw {code:'42501'};}};assert.equal((await photoHandler(denied)(req())).status,403);assert.equal(buckets+downloads+finishes,0);});
await test('Verified bytes are hashed and finalized; retry is delegated to SQL receipt',async()=>{const h=photoHandler(dep);assert.equal((await h(req())).status,200);assert.equal((await h(req())).status,200);assert.equal(finishes,2);});
await test('Corruption, oversize and non-JPEG files never reach finalization',async()=>{for(const bad of [new Uint8Array([255,216,255,1,255,217]),new Uint8Array(4194305),new Uint8Array([1,2,3,4])]){assert.equal((await photoHandler({...dep,download:async()=>bad})(req())).status,409);}assert.equal(finishes,2);});
await test('Permission revocation after download is rechecked during finalization',async()=>{const r=await photoHandler({...dep,finish:async()=>{throw {code:'42501'};}})(req());assert.equal(r.status,403);assert.equal((await r.json()).sessionId,undefined);});
await test('Public or unavailable bucket aborts before download',async()=>{const before=downloads;assert.equal((await photoHandler({...dep,bucket:async()=>{throw new Error('Public bucket');}})(req())).status,409);assert.equal(downloads,before);});
await test('Malformed actions and large metadata fail without privileged effects',async()=>{const before=buckets;assert.equal((await photoHandler(dep)(req({...body,action:'delete'}))).status,400);assert.equal((await photoHandler(dep)(req({...body,extra:'x'.repeat(16001)}))).status,413);assert.equal(buckets,before);});
await test('Prepare uses stable caller command and returns only authorized info',async()=>{const r=await photoHandler(dep)(req({...body,action:'prepare',commandId:uuid,payload:{id:uuid}}));assert.equal(r.status,200);assert.equal(prepares,1);assert.equal((await r.json()).path,info.path);});
console.log(`${passed} photo function checks passed with simulated Auth and Storage dependencies.`);
