import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
let n=2000,passed=0; const id=()=>`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`;
const w=id(),admin=id(),tech=id(),other=id(),ad=id(),td=id(),od=id(),order=id(),task=id(),photo=id(),command=id(),hash='ab'.repeat(32);
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL(`../supabase/migrations/${f}`,import.meta.url),'utf8'));await db.query('insert into auth.users values($1),($2),($3)',[admin,tech,other]);await db.query("insert into private.workshops(id,name) values($1,'Fictional photo test')",[w]);await db.query("insert into private.members values($1,$2,'Admin','admin',true,true)",[w,admin]);return db;}
async function login(db,u,d){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[d,u]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,session_id:d})]);await db.exec('set role authenticated');}
const snap=async(db,d)=>(await db.query('select public.device_snapshot($1,$2) r',[w,d])).rows[0].r;
const cmd=async(db,d,c,a,p)=>(await db.query('select public.photo_command($1,$2,$3,$4,$5) r',[w,d,c,a,p])).rows[0].r;
const final=async(db,d,p,u=tech,h=hash)=>{await db.exec('reset role;set role service_role');return(await db.query('select public.photo_finalize($1,$2,$3,$4,$2,$5,5) r',[w,d,p,u,h])).rows[0].r;};
const meta={id:photo,orderId:order,originalDeviceId:td,sha256:hash,size:5,mime:'image/jpeg',caption:'Fictional damaged part',capturedAt:new Date().toISOString()};
const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
const db=await setup(),target=await setup();let info,archive;
try{
 await db.query("insert into private.members values($1,$2,'Technician','technician',false,true),($1,$3,'Other','technician',false,true)",[w,tech,other]);
 await login(db,admin,ad);await snap(db,ad);
 const op={id:id(),orderId:order,actorId:admin,kind:'receive',baseRevision:0,at:new Date().toISOString(),payload:{plate:'1234ABC',country:'ES',vin:'PHOTO-FICTIONAL',vehicle:'Fictional',engine:'2020',client:'Fictional owner',phone:'',km:10,symptom:'Fictional',tasks:[{id:task,title:'Inspect',assignees:[tech],estimateMinutes:30}]}};
 await db.query('select public.apply_operation($1,$2,$3)',[w,ad,op]);await login(db,tech,td);await snap(db,td);await db.query("select set_config('storage.operation','object.head_authenticated_info',false)");
 await test('Authorized prepare is stable after lost response and metadata ID reuse is rejected',async()=>{info=await cmd(db,td,command,'photo_prepare',meta);assert.equal(info.status,'pending');assert.deepEqual(await cmd(db,td,command,'photo_prepare',meta),info);await assert.rejects(()=>cmd(db,td,command,'photo_prepare',{...meta,caption:'Changed'}),/Command ID reused/);await assert.rejects(()=>cmd(db,td,id(),'photo_prepare',{...meta,sha256:'cd'.repeat(32)}),/Photo ID reused/);});
 await test('Assigned uploader may INSERT only exact reserved path and cannot fabricate evidence',async()=>{await assert.rejects(()=>db.query("insert into storage.objects(bucket_id,name) values('tallerflow-photos',$1)",[`${w}/${order}/${id()}.jpg`]),/row-level security/);await db.query("insert into storage.objects(bucket_id,name) values('tallerflow-photos',$1)",[info.path]);await assert.rejects(()=>db.query('select public.photo_finalize($1,$2,$3,$4,$2,$5,5)',[w,td,photo,tech,hash]),/permission denied/);});
 await test('Immutable file denies all direct reads, UPDATE, DELETE and signed URLs',async()=>{assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);assert.equal((await db.query("update storage.objects set metadata='{}' returning name")).rows.length,0);assert.equal((await db.query('delete from storage.objects returning name')).rows.length,0);await db.query("select set_config('storage.operation','object.sign',false)");assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);await db.query("select set_config('storage.operation','object.head_authenticated_info',false)");});
 await test('Direct object GET is denied and authorized download metadata is isolated by role and session',async()=>{await db.query("select set_config('storage.operation','object.get_authenticated',false)");assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);const allowed=(await db.query('select public.photo_download_info($1,$2,$3) r',[w,td,photo])).rows[0].r;assert.equal(allowed.sha256,hash);await login(db,other,od);await snap(db,od);await assert.rejects(()=>db.query('select public.photo_download_info($1,$2,$3)',[w,od,photo]),/not available/);await login(db,tech,td);await db.query("select set_config('storage.operation','object.head_authenticated_info',false)");});
 await test('Pending verification blocks closure and document issuance',async()=>{await db.exec('reset role');await assert.rejects(()=>db.query("insert into private.close_requests(workshop_id,id,order_id,revision,status,requested_by) values($1,$2,$3,0,'active',$4)",[w,id(),order,admin]),/Photos pending/);await assert.rejects(()=>db.query("insert into private.documents(workshop_id,order_id,type,version,recipient_id,snapshot) values($1,$2,'work_note',1,$3,'{}')",[w,order,admin]),/Photos pending/);});
 await test('Verifier rejects changed hash and attaches verified file once across retries',async()=>{await assert.rejects(()=>final(db,td,photo,tech,'cd'.repeat(32)),/hash or size/);assert.equal((await final(db,td,photo)).status,'attached');assert.equal((await final(db,td,photo)).status,'attached');await login(db,tech,td);const s=await snap(db,td);assert.equal(s.photoManifest.length,1);assert.equal(s.orders[0].photos.length,1);assert.equal(s.orders[0].revision,2);});
 await test('Unassigned account cannot read another operator evidence or reserve its order',async()=>{await login(db,other,od);await snap(db,od);assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);await assert.rejects(()=>cmd(db,od,id(),'photo_prepare',{...meta,id:id(),originalDeviceId:od}),/Order permission/);await assert.rejects(()=>db.query('select public.photo_upload_info($1,$2,$3)',[w,od,photo]),/not available/);});
 await test('Office reads files and session revocation immediately invalidates a previously permitted file',async()=>{await login(db,admin,ad);assert.equal((await db.query('select public.photo_download_info($1,$2,$3) r',[w,ad,photo])).rows[0].r.sha256,hash);await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[ad]);await db.exec('set role authenticated');await assert.rejects(()=>db.query('select public.photo_download_info($1,$2,$3)',[w,ad,photo]),/session/i);await login(db,admin,ad);});
 await test('Complete export includes original file manifest and no Storage or Auth table writes',async()=>{archive=(await db.query('select public.export_workshop($1,$2) r',[w,ad])).rows[0].r;assert.equal(archive.databaseVersion,13);assert.equal(archive.photoFiles[0].filePresent,true);assert.equal(archive.tables.order_photos[0].sha256,hash);assert.equal(archive.tables.storage,undefined);assert.equal(archive.tables.auth,undefined);});
 const newDev=id();await login(target,admin,newDev);await snap(target,newDev);
 await test('Independent recovery rejects absent attached-file manifest before any data is restored',async()=>{const bad=structuredClone(archive);bad.photoFiles=[];await assert.rejects(()=>target.query('select public.restore_workshop($1,$2,$3,$4)',[w,newDev,id(),bad]),/manifest missing/);assert.equal((await snap(target,newDev)).orders.length,0);});
 const restoreId=id();await test('Independent recovery retires old devices and requires original files before new work',async()=>{await target.query('select public.restore_workshop($1,$2,$3,$4)',[w,newDev,restoreId,archive]);assert.equal((await snap(target,newDev)).restoreFilesPending,true);const original={...op,id:id(),actorId:admin,kind:'note',payload:{text:'Before file recovery'}};await assert.rejects(()=>target.query('select public.apply_operation($1,$2,$3)',[w,newDev,original]),/Restore original/);await target.exec('reset role');assert.ok((await target.query('select retired_at from private.devices where id=$1',[td])).rows[0].retired_at);await login(target,admin,newDev);});
 await test('Restoration uploads remain immutable and repeated verification clears the file gate without rewriting order',async()=>{const p=(await target.query('select public.photo_upload_info($1,$2,$3) r',[w,newDev,photo])).rows[0].r;await target.query("insert into storage.objects(bucket_id,name) values('tallerflow-photos',$1)",[p.path]);await final(target,newDev,photo,admin);await final(target,newDev,photo,admin);await login(target,admin,newDev);const s=await snap(target,newDev);assert.equal(s.restoreFilesPending,false);assert.equal(s.orders[0].revision,2);assert.equal(s.orders[0].photos.length,1);assert.deepEqual((await target.query('select public.restore_workshop($1,$2,$3,$4) r',[w,newDev,restoreId,archive])).rows[0].r.restored,true);});
 await test('Recovered original device evidence needs office review and cannot be attached by its operator',async()=>{const pending=id();await login(db,tech,td);await cmd(db,td,id(),'photo_prepare',{...meta,id:pending});await db.exec('reset role');await db.query("update private.devices set retired_at=now(),retirement_reason='Fictional lost equipment' where id=$1",[td]);await db.query('delete from auth.sessions where id=$1',[td]);const replacement=id();await login(db,tech,replacement);await snap(db,replacement);const recovered=await cmd(db,replacement,id(),'photo_prepare',{...meta,id:pending});await db.query("insert into storage.objects(bucket_id,name) values('tallerflow-photos',$1)",[recovered.path]);assert.equal((await final(db,replacement,pending)).status,'review');await login(db,tech,replacement);await assert.rejects(()=>cmd(db,replacement,id(),'photo_approve',{id:pending,revision:2,reason:'Fictional review'}),/Office review/);await login(db,admin,ad);assert.equal((await cmd(db,ad,id(),'photo_approve',{id:pending,revision:2,reason:'Verified fictional recovery'})).status,'attached');assert.equal((await snap(db,ad)).orders[0].photos.length,2);});
 console.log(`${passed} photo checks passed in local PostgreSQL/PGlite, including an independent recovery database. Storage HTTP and camera remain separate validations.`);
}finally{await db.close();await target.close();}
