import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';import assert from 'node:assert/strict';
let n=7000,passed=0;const id=()=>`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`;
const w=id(),office=id(),tech=id(),other=id(),od=id(),td=id(),xd=id(),order=id(),task=id(),inspection=id(),row=id();
const db=new PGlite();
await db.exec("create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid not null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");
await db.exec(await readFile(new URL('./storage_fixture.sql',import.meta.url),'utf8'));
for(const f of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1),($2),($3)',[office,tech,other]);
await db.query("insert into private.workshops(id,name) values($1,'Fictional quotes')",[w]);
await db.query("insert into private.members values($1,$2,'Office','admin',true,true),($1,$3,'Technician','technician',false,true),($1,$4,'Other','technician',false,true)",[w,office,tech,other]);
let actor,device;
async function login(u,d){await db.exec('reset role');await db.query('insert into auth.sessions values($1,$2) on conflict do nothing',[d,u]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:u,session_id:d})]);await db.exec('set role authenticated');actor=u;device=d;await snap();}
const snap=async()=>(await db.query('select public.device_snapshot($1,$2) r',[w,device])).rows[0].r;
const command=async(action,p)=>(await db.query('select public.reliability_command($1,$2,$3,$4,$5) r',[w,device,id(),action,p])).rows[0].r;
async function op(kind,p,{opid=id(),revision}={}){const s=await snap();const o=s.orders.find(o=>o.id===order);const record={id:opid,orderId:order,actorId:actor,kind,at:new Date().toISOString(),baseRevision:revision??o?.revision??0,payload:p};return {record,result:(await db.query('select public.apply_operation($1,$2,$3) r',[w,device,record])).rows[0].r};}
const quote=id(),line=id();
const payload=(version=0)=>({id:quote,expectedVersion:version,title:'Fictional repair',reason:'Initial scope',validUntil:'2026-11-01T00:00:00Z',lines:[{id:line,taskId:task,description:'Fictional scope',laborMinutes:30,parts:[{reference:'OIL',description:'Fictional oil',unit:'litre',quantityMilli:1500,unitPriceCents:1001,taxBps:2100,discountBps:1000}]}]});
const decision=(version=1,accepted=true)=>({quoteId:quote,version,customer:'Fictional private owner',channel:'telephone',evidence:'Fictional call with owner',reason:'Customer decision',decisions:[{lineId:line,accepted}]});
const test=async(name,f)=>{await f();passed++;console.log('PASS '+name);};
try {
 await login(office,od);assert.equal((await op('receive',{plate:'8801FIC',country:'ES',vin:'QUOTES-FICTIONAL',vehicle:'Fictional',engine:'2020',client:'Fictional private owner',phone:'600000000',km:10,symptom:'Fictional symptom',tasks:[{id:task,title:'Check',assignees:[tech],estimateMinutes:30}]})).result.status,'accepted');
 let first, accepted;
 await test('Draft snapshots decimals and taxes without authorizing or consuming stock',async()=>{const before=(await snap()).orders[0];first=await op('quote_draft',payload());assert.equal(first.result.status,'accepted');const after=(await snap()).orders[0];assert.deepEqual(after.tasks,before.tasks);assert.deepEqual(after.parts,before.parts);const q=after.quoteLedger.versions[0];assert.equal(q.totalCents,4540);assert.equal(q.lines[0].components[1].grossCents,1502);assert.equal(q.lines[0].components[1].netCents,1352);});
 await test('Lost response is once; altered idempotency identity is refused',async()=>{assert.deepEqual((await db.query('select public.apply_operation($1,$2,$3) r',[w,device,first.record])).rows[0].r,first.result);await assert.rejects(()=>db.query('select public.apply_operation($1,$2,$3)',[w,device,{...first.record,payload:{...payload(),title:'Altered'}}]),/Idempotency/);assert.equal((await snap()).orders[0].quoteLedger.versions.length,1);});
 await test('Office records exact-version evidence and authorizes only that task',async()=>{accepted=await op('quote_decision',decision());assert.equal(accepted.result.status,'accepted');const o=(await snap()).orders[0];assert.equal(o.tasks[0].authorized,true);assert.equal(o.tasks[0].approvedCents,4540);assert.equal(o.tasks[0].authorization.decisionId,accepted.record.id);assert.equal(o.tasks[0].authorization.quoteId,quote);assert.equal(o.quoteLedger.decisions.length,1);});
 await test('Operators receive no quote documents, cannot decide, and cannot execute helpers',async()=>{await db.exec('reset role');await db.query('update private.members set see_prices=true where workshop_id=$1 and user_id=$2',[w,tech]);await login(tech,td);assert.equal((await snap()).orders[0].tasks[0].approvedCents,4540);assert.equal((await snap()).orders[0].quoteLedger,undefined);assert.equal((await op('quote_draft',payload(1))).result.status,'conflict');assert.equal((await op('quote_decision',decision())).result.status,'conflict');await assert.rejects(()=>db.query('select private.prepare_quote($1,$2,$3,$4,now(),0)',[{},payload(),tech,id()]),/permission denied/);await login(office,od);});
 await test('An extension preserves the original and its rejection preserves approved work',async()=>{const before=(await snap()).orders[0];assert.equal((await op('quote_draft',payload(1))).result.status,'accepted');let o=(await snap()).orders[0];assert.deepEqual(o.tasks,before.tasks);assert.deepEqual(o.quoteLedger.versions[0],before.quoteLedger.versions[0]);assert.equal((await op('quote_decision',decision(1))).result.status,'conflict');assert.equal((await op('quote_decision',decision(2,false))).result.status,'accepted');o=(await snap()).orders[0];assert.deepEqual(o.tasks,before.tasks);assert.equal(o.quoteLedger.decisions[1].decisions[0].approvedCents,0);});
 await test('Batch below performed work, duplicate decisions, stale revisions and forged amount fail atomically',async()=>{assert.equal((await op('billable',{taskId:task,minutes:120,reason:'Fictional reviewed time'})).result.status,'accepted');assert.equal((await op('quote_draft',payload(2))).result.status,'accepted');const before=(await snap()).orders[0];for(const p of [decision(3),{...decision(3),approvedCents:1},{...decision(3),decisions:[...decision(3).decisions,...decision(3).decisions]}])assert.equal((await op('quote_decision',p)).result.status,'conflict');assert.deepEqual((await snap()).orders[0].quoteLedger,before.quoteLedger);assert.equal((await op('quote_draft',payload(3),{revision:0})).result.status,'conflict');assert.equal((await op('billable',{taskId:task,minutes:0,reason:'Fictional correction'})).result.status,'accepted');});
 await test('Changed prices require a reviewed current version',async()=>{assert.equal((await op('pricing_review',{target:'labor',targetId:task,unitPriceCents:5000,taxBps:2100,discountBps:0,charge:true,reason:'Fictional rate review'})).result.status,'accepted');assert.equal((await op('quote_decision',decision(3))).result.status,'conflict');assert.equal((await op('quote_draft',payload(3))).result.status,'accepted');assert.equal((await op('quote_decision',decision(4))).result.status,'accepted');const q=(await snap()).orders[0].quoteLedger.versions[3];assert.equal(q.lines[0].components[0].unitPriceCents,5000);});
 await test('Malformed lines, duplicates, unknown tasks, empty scope and extra totals retain conflict evidence',async()=>{for(const p of [{...payload(4),totalCents:1},{...payload(4),lines:[]},{...payload(4),lines:[...payload(4).lines,...payload(4).lines]},{...payload(4),lines:[{...payload(4).lines[0],taskId:id()}]},{...payload(4),lines:[{...payload(4).lines[0],laborMinutes:0,parts:[]}]}])assert.equal((await op('quote_draft',p)).result.status,'conflict');assert.equal((await snap()).orders[0].quoteLedger.versions.length,4);});
 await test('Complete backup includes immutable versions, decisions, operation originals and audit',async()=>{const a=(await db.query('select public.export_workshop($1,$2) r',[w,od])).rows[0].r;assert.equal(a.tables.orders[0].data.quoteLedger.versions.length,4);assert.equal(a.tables.orders[0].data.quoteLedger.decisions.length,3);assert.ok(a.tables.operations.find(v=>v.id===accepted.record.id));assert.equal(a.tables.audit.filter(v=>v.kind==='quote_draft').length,4);});
 console.log(`${passed} quote checks passed in PostgreSQL/PGlite with synthetic Auth.`);
} finally {await db.close();}
